/**
 * Lista mestre de categorias de serviços (substitui o enum fechado de 8
 * categorias). Texto livre no banco (service_listings.service_type) — o
 * valor salvo é o próprio nome da categoria, igual a PRODUCT_CATEGORIES.
 */
import {
  Activity,
  Apple,
  Armchair,
  ArrowLeftRight,
  Baby,
  BadgeCheck,
  Banknote,
  BatteryCharging,
  Beef,
  Bike,
  Bone,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarCheck,
  Camera,
  Car,
  ClipboardCheck,
  ClipboardList,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Cpu,
  Croissant,
  Disc,
  Dog,
  DoorClosed,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Eye,
  Factory,
  FileCheck,
  FileText,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Gamepad2,
  Gavel,
  GraduationCap,
  Hammer,
  Hand,
  Handshake,
  HardHat,
  Headphones,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hotel,
  HousePlus,
  IceCreamCone,
  Key,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Megaphone,
  Mic,
  Music,
  Network,
  Package,
  PackageSearch,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  PenTool,
  Pencil,
  PencilRuler,
  PersonStanding,
  Pill,
  Pizza,
  Plane,
  Presentation,
  Printer,
  Radar,
  Recycle,
  RotateCcw,
  Ruler,
  Sandwich,
  Scale,
  ScanLine,
  School,
  Scissors,
  Search,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Swords,
  Syringe,
  Target,
  Tractor,
  Trash2,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Video,
  Volume2,
  Warehouse,
  Waves,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface ServiceCategoryGroup {
  emoji: string;
  group: string;
  icon: LucideIcon;
  items: string[];
}

export const SERVICE_CATEGORY_GROUPS: ServiceCategoryGroup[] = [
  {
    emoji: "🏥",
    group: "Saúde",
    icon: Stethoscope,
    items: [
      "Clínicas Médicas",
      "Dentistas",
      "Psicólogos",
      "Fisioterapeutas",
      "Nutricionistas",
      "Laboratórios",
      "Farmácias",
      "Clínicas Veterinárias",
      "Fonoaudiólogos",
      "Terapias Integrativas",
      "Cardiologistas",
      "Dermatologistas",
      "Oftalmologistas",
      "Ortopedistas",
      "Ginecologistas",
      "Pediatras",
      "Urologistas",
      "Clínicas de Imagem",
      "Home Care",
      "Acupuntura",
      "Quiropraxia",
      "Massoterapia",
      "Clínicas de Vacinação",
      "Clínicas de Reabilitação",
      "Podologia",
    ],
  },
  {
    emoji: "💄",
    group: "Beleza e Estética",
    icon: Scissors,
    items: [
      "Salões de Beleza",
      "Barbearias",
      "Manicure e Pedicure",
      "Estética Facial",
      "Estética Corporal",
      "Maquiagem",
      "Depilação",
      "Design de Sobrancelhas",
      "Alongamento de Unhas",
      "Cabeleireiros",
    ],
  },
  {
    emoji: "🚗",
    group: "Automotivo",
    icon: Car,
    items: [
      "Oficinas Mecânicas",
      "Auto Elétricas",
      "Borracharias",
      "Guinchos",
      "Lava Jatos",
      "Funilaria",
      "Pintura Automotiva",
      "Troca de Óleo",
      "Som Automotivo",
      "Insulfilm",
      "Alinhamento e Balanceamento",
      "Vistoria Veicular",
      "Despachante Veicular",
      "Rastreamento Veicular",
      "Locação de Carros",
      "Blindagem",
      "Estética Automotiva",
      "Martelinho de Ouro",
      "Chave Automotiva",
      "Socorro Mecânico",
    ],
  },
  {
    emoji: "🏠",
    group: "Construção e Reformas",
    icon: HardHat,
    items: [
      "Pedreiros",
      "Pintores",
      "Eletricistas",
      "Encanadores",
      "Gesseiros",
      "Serralheiros",
      "Marceneiros",
      "Vidraceiros",
      "Telhadistas",
      "Engenheiros",
    ],
  },
  {
    emoji: "🔧",
    group: "Manutenção Residencial",
    icon: Wrench,
    items: [
      "Chaveiros",
      "Dedetização",
      "Jardinagem",
      "Limpeza Residencial",
      "Limpeza de Piscinas",
      "Segurança Residencial",
      "Instalação de Câmeras",
      "Montagem de Móveis",
      "Assistência Técnica",
      "Mudanças e Fretes",
    ],
  },
  {
    emoji: "🐶",
    group: "Pets",
    icon: PawPrint,
    items: [
      "Pet Shops",
      "Banho e Tosa",
      "Adestramento",
      "Hospedagem Pet",
      "Passeadores de Cães",
    ],
  },
  {
    emoji: "🍔",
    group: "Alimentação",
    icon: UtensilsCrossed,
    items: [
      "Restaurantes",
      "Lanchonetes",
      "Pizzarias",
      "Padarias",
      "Confeitarias",
      "Marmitarias",
      "Food Trucks",
      "Cafeterias",
      "Churrascarias",
      "Sorveterias",
    ],
  },
  {
    emoji: "🏨",
    group: "Turismo e Hospedagem",
    icon: Plane,
    items: [
      "Hotéis",
      "Pousadas",
      "Agências de Turismo",
      "Guias Turísticos",
      "Locação de Veículos",
    ],
  },
  {
    emoji: "📚",
    group: "Educação",
    icon: GraduationCap,
    items: [
      "Escolas",
      "Cursos Profissionalizantes",
      "Idiomas",
      "Aulas Particulares",
      "Reforço Escolar",
      "Escolas Particulares",
      "Creches",
      "Cursos Técnicos",
      "Preparatórios para Concursos",
      "Preparatórios para Vestibular",
      "Cursos de Informática",
      "Cursos de Música",
      "Cursos de Artes",
      "Treinamentos Corporativos",
      "Educação Financeira",
    ],
  },
  {
    emoji: "💻",
    group: "Tecnologia",
    icon: Laptop,
    items: [
      "Desenvolvimento de Sites",
      "Desenvolvimento de Apps",
      "Suporte em TI",
      "Redes de Computadores",
      "Marketing Digital",
      "Criação de Lojas Virtuais",
      "Hospedagem de Sites",
      "SEO",
      "Gestão de Redes Sociais",
      "Tráfego Pago",
      "Design Gráfico",
      "Edição de Vídeo",
      "Produção de Conteúdo",
      "Segurança Digital",
      "Consultoria em IA",
    ],
  },
  {
    emoji: "📈",
    group: "Profissionais Liberais",
    icon: Briefcase,
    items: [
      "Advogados",
      "Contadores",
      "Corretores de Imóveis",
      "Consultores Financeiros",
      "Despachantes",
    ],
  },
  {
    emoji: "🎉",
    group: "Eventos",
    icon: PartyPopper,
    items: [
      "Fotógrafos",
      "Filmagens",
      "DJs",
      "Buffets",
      "Decoração de Festas",
      "Organização de Eventos",
      "Cerimonialistas",
      "Casas de Festas",
      "Aluguel de Brinquedos",
      "Aluguel de Mesas e Cadeiras",
      "Som e Iluminação",
      "Cabines Fotográficas",
      "Segurança para Eventos",
      "Garçons",
      "Bartenders",
    ],
  },
  {
    emoji: "👔",
    group: "Serviços Empresariais",
    icon: Building2,
    items: [
      "Recursos Humanos",
      "Segurança do Trabalho",
      "Consultoria Empresarial",
      "Cobrança e Recuperação",
      "Terceirização de Serviços",
    ],
  },
  {
    emoji: "🚚",
    group: "Transporte",
    icon: Truck,
    items: [
      "Motoboys",
      "Transportadoras",
      "Fretes",
      "Táxis",
      "Motoristas Particulares",
    ],
  },
  {
    emoji: "🏋️",
    group: "Esporte e Fitness",
    icon: Dumbbell,
    items: [
      "Academias",
      "Personal Trainers",
      "Pilates",
      "CrossFit",
      "Natação",
      "Artes Marciais",
      "Yoga",
      "Dança",
      "Treinamento Funcional",
      "Escolinhas de Futebol",
    ],
  },
  {
    emoji: "🏡",
    group: "Imóveis",
    icon: Home,
    items: [
      "Imobiliárias",
      "Avaliação de Imóveis",
      "Administração de Condomínios",
      "Regularização de Imóveis",
      "Topografia",
      "Arquitetura",
      "Design de Interiores",
      "Paisagismo",
      "Inspeção Predial",
      "Financiamento Imobiliário",
    ],
  },
  {
    emoji: "⚡",
    group: "Energia e Utilidades",
    icon: Zap,
    items: [
      "Energia Solar",
      "Instalação Elétrica",
      "Automação Residencial",
      "Geradores",
      "Poços Artesianos",
      "Purificadores de Água",
      "Instalação de Gás",
      "Aquecimento Solar",
      "Climatização",
      "Refrigeração",
    ],
  },
  {
    emoji: "🚜",
    group: "Agronegócio",
    icon: Tractor,
    items: [
      "Assistência Agrícola",
      "Veterinários Rurais",
      "Irrigação",
      "Máquinas Agrícolas",
      "Drones Agrícolas",
      "Silagem",
      "Cercamento Rural",
      "Consultoria Agronômica",
      "Transporte de Gado",
      "Armazenagem Agrícola",
    ],
  },
  {
    emoji: "🏭",
    group: "Indústria",
    icon: Factory,
    items: [
      "Soldagem Industrial",
      "Usinagem",
      "Caldeiraria",
      "Automação Industrial",
      "Manutenção Industrial",
      "Controle de Qualidade",
      "Engenharia Mecânica",
      "Engenharia Elétrica",
      "Logística Industrial",
      "Segurança Industrial",
    ],
  },
  {
    emoji: "🎨",
    group: "Arte e Comunicação",
    icon: Palette,
    items: [
      "Agências de Publicidade",
      "Comunicação Visual",
      "Gráficas",
      "Impressão 3D",
      "Produção Musical",
      "Estúdios de Gravação",
      "Locução",
      "Ilustração",
      "Fotografia Comercial",
      "Produção Audiovisual",
    ],
  },
  {
    emoji: "👶",
    group: "Serviços Familiares",
    icon: Baby,
    items: [
      "Babás",
      "Cuidadores de Idosos",
      "Acompanhantes Hospitalares",
      "Recreação Infantil",
      "Orientação Familiar",
      "Aulas para Crianças",
      "Transporte Escolar",
      "Casas de Repouso",
      "Berçários",
      "Monitoria Escolar",
    ],
  },
  {
    emoji: "🛡️",
    group: "Segurança",
    icon: Shield,
    items: [
      "Vigilância Patrimonial",
      "Portaria",
      "Monitoramento 24h",
      "Escolta",
      "Investigação Particular",
      "Segurança Eletrônica",
      "Alarmes",
      "Controle de Acesso",
      "Portões Automáticos",
      "Segurança Empresarial",
    ],
  },
  {
    emoji: "💰",
    group: "Financeiro",
    icon: Landmark,
    items: [
      "Correspondente Bancário",
      "Seguros",
      "Consórcios",
      "Planejamento Financeiro",
      "Recuperação de Crédito",
      "Investimentos",
      "Financiamentos",
      "Câmbio",
      "Crédito Rural",
      "Crédito Imobiliário",
    ],
  },
  {
    emoji: "⚖️",
    group: "Jurídico",
    icon: Scale,
    items: [
      "Direito Trabalhista",
      "Direito Previdenciário",
      "Direito Civil",
      "Direito Criminal",
      "Direito Empresarial",
      "Direito Imobiliário",
      "Direito Tributário",
      "Mediação",
      "Arbitragem",
      "Assessoria Jurídica",
    ],
  },
  {
    emoji: "🛍️",
    group: "Comércio e Negócios",
    icon: ShoppingBag,
    items: [
      "Representação Comercial",
      "Franquias",
      "Distribuidoras",
      "Importação",
      "Exportação",
      "E-commerce",
      "Marketplace",
      "Pesquisa de Mercado",
      "Auditoria",
      "Compliance",
    ],
  },
  {
    emoji: "🚚",
    group: "Logística",
    icon: PackageSearch,
    items: [
      "Entregas Expressas",
      "Armazenagem",
      "Centros de Distribuição",
      "Transporte Refrigerado",
      "Logística Reversa",
      "Courier",
      "Mudanças Interestaduais",
      "Frete Pesado",
      "Transporte Executivo",
    ],
  },
  {
    emoji: "🌿",
    group: "Meio Ambiente",
    icon: Leaf,
    items: [
      "Licenciamento Ambiental",
      "Gestão de Resíduos",
      "Coleta Seletiva",
      "Reciclagem",
      "Consultoria Ambiental",
      "Recuperação de Áreas",
      "Educação Ambiental",
      "Análises Ambientais",
      "Tratamento de Água",
      "Tratamento de Esgoto",
    ],
  },
  {
    emoji: "🔍",
    group: "Serviços Diversos",
    icon: Sparkles,
    items: [
      "Tradução",
      "Intérprete",
      "Coaching",
      "Mentoria",
      "Recrutamento e Seleção",
      "Pesquisa Particular",
      "Digitalização de Documentos",
      "Certificação Digital",
      "Despachante Documental",
      "Leiloeiros",
      "Perícias Técnicas",
      "Avaliação de Bens",
      "Consultoria Estratégica",
      "Atendimento Virtual",
      "Outros Serviços",
    ],
  },
  {
    emoji: "🚜",
    group: "Máquinas e Tratores",
    icon: Construction,
    items: [
      "Venda de Tratores",
      "Aluguel de Tratores",
      "Manutenção de Tratores",
      "Revisão de Tratores",
      "Peças para Tratores",
      "Tratores de Esteira",
      "Implementos Agrícolas",
      "Colheitadeiras",
      "Manutenção de Colheitadeiras",
      "Plantadeiras",
      "Manutenção de Plantadeiras",
      "Pulverizadores Agrícolas",
      "Pulverização Aérea",
      "Roçadeiras Agrícolas",
      "Grades Agrícolas",
      "Arados",
      "Subsoladores",
      "Carretas Agrícolas",
      "Pá Carregadeira",
      "Retroescavadeira",
      "Escavadeira Hidráulica",
      "Motoniveladora",
      "Rolo Compactador",
      "Guindastes",
      "Munck",
      "Empilhadeiras",
      "Manutenção de Máquinas Pesadas",
      "Aluguel de Máquinas Pesadas",
      "Venda de Máquinas Pesadas",
      "Peças para Máquinas Pesadas",
      "Pneus para Máquinas Agrícolas",
      "Hidráulica Industrial",
      "Solda para Máquinas Agrícolas",
      "Usinagem de Peças Agrícolas",
      "Revisão de Motores Diesel",
      "Injeção Eletrônica Diesel",
      "Turbina Diesel",
      "Transporte de Máquinas Pesadas",
      "Guincho para Máquinas Pesadas",
      "Operador de Máquinas Pesadas",
      "Locação de Operadores Agrícolas",
      "Terraplanagem",
      "Nivelamento de Terreno",
      "Escavação",
      "Demolição com Máquinas",
      "Britagem",
      "Perfuração de Poços",
      "Irrigação por Pivô",
      "Construção de Silos",
      "Funilaria de Máquinas Agrícolas",
      "Pintura de Máquinas Agrícolas",
      "Diagnóstico Eletrônico de Máquinas",
      "Aluguel de Caçambas",
      "Aluguel de Compressores Industriais",
      "Locação de Equipamentos para Construção",
      "Manutenção de Retroescavadeiras",
      "Manutenção de Escavadeiras",
      "Reforma de Tratores",
      "Comércio de Peças Agrícolas",
      "Assistência Técnica para Tratores",
    ],
  },
];

/** Ícone específico de cada item (mais preciso que o ícone do grupo). */
export const SERVICE_ITEM_ICONS: Record<string, LucideIcon> = {
  "Clínicas Médicas": Stethoscope,
  Dentistas: Smile,
  Psicólogos: Brain,
  Fisioterapeutas: Activity,
  Nutricionistas: Apple,
  Laboratórios: FlaskConical,
  Farmácias: Pill,
  "Clínicas Veterinárias": PawPrint,
  Fonoaudiólogos: Mic,
  "Terapias Integrativas": Flower2,
  Cardiologistas: HeartPulse,
  Dermatologistas: Sparkles,
  Oftalmologistas: Eye,
  Ortopedistas: Bone,
  Ginecologistas: HeartPulse,
  Pediatras: Baby,
  Urologistas: Droplet,
  "Clínicas de Imagem": ScanLine,
  "Home Care": HousePlus,
  Acupuntura: Sparkles,
  Quiropraxia: PersonStanding,
  Massoterapia: Hand,
  "Clínicas de Vacinação": Syringe,
  "Clínicas de Reabilitação": Activity,
  Podologia: Footprints,
  "Salões de Beleza": Scissors,
  Barbearias: Scissors,
  "Manicure e Pedicure": Hand,
  "Estética Facial": Smile,
  "Estética Corporal": Sparkles,
  Maquiagem: Palette,
  Depilação: Zap,
  "Design de Sobrancelhas": Pencil,
  "Alongamento de Unhas": Hand,
  Cabeleireiros: Scissors,
  "Oficinas Mecânicas": Wrench,
  "Auto Elétricas": Zap,
  Borracharias: Disc,
  Guinchos: Truck,
  "Lava Jatos": Droplets,
  Funilaria: Hammer,
  "Pintura Automotiva": SprayCan,
  "Troca de Óleo": Droplet,
  "Som Automotivo": Volume2,
  Insulfilm: Layers,
  "Alinhamento e Balanceamento": Disc,
  "Vistoria Veicular": ClipboardCheck,
  "Despachante Veicular": FileText,
  "Rastreamento Veicular": MapPin,
  "Locação de Carros": Car,
  Blindagem: Shield,
  "Estética Automotiva": Sparkles,
  "Martelinho de Ouro": Hammer,
  "Chave Automotiva": Key,
  "Socorro Mecânico": LifeBuoy,
  Pedreiros: HardHat,
  Pintores: Paintbrush,
  Eletricistas: Zap,
  Encanadores: Droplet,
  Gesseiros: Layers,
  Serralheiros: Wrench,
  Marceneiros: Hammer,
  Vidraceiros: Layers,
  Telhadistas: Home,
  Engenheiros: Ruler,
  Chaveiros: Key,
  Dedetização: Bug,
  Jardinagem: Sprout,
  "Limpeza Residencial": Sparkles,
  "Limpeza de Piscinas": Waves,
  "Segurança Residencial": Shield,
  "Instalação de Câmeras": Camera,
  "Montagem de Móveis": Wrench,
  "Assistência Técnica": Settings,
  "Mudanças e Fretes": Truck,
  "Pet Shops": PawPrint,
  "Banho e Tosa": Droplets,
  Adestramento: Dog,
  "Hospedagem Pet": Home,
  "Passeadores de Cães": Footprints,
  Restaurantes: UtensilsCrossed,
  Lanchonetes: Sandwich,
  Pizzarias: Pizza,
  Padarias: Croissant,
  Confeitarias: Cake,
  Marmitarias: UtensilsCrossed,
  "Food Trucks": Truck,
  Cafeterias: Coffee,
  Churrascarias: Beef,
  Sorveterias: IceCreamCone,
  Hotéis: Hotel,
  Pousadas: Home,
  "Agências de Turismo": Plane,
  "Guias Turísticos": Compass,
  "Locação de Veículos": Car,
  Escolas: School,
  "Cursos Profissionalizantes": GraduationCap,
  Idiomas: Languages,
  "Aulas Particulares": BookOpen,
  "Reforço Escolar": BookOpen,
  "Escolas Particulares": School,
  Creches: Baby,
  "Cursos Técnicos": GraduationCap,
  "Preparatórios para Concursos": ClipboardList,
  "Preparatórios para Vestibular": ClipboardList,
  "Cursos de Informática": Laptop,
  "Cursos de Música": Music,
  "Cursos de Artes": Palette,
  "Treinamentos Corporativos": Presentation,
  "Educação Financeira": Calculator,
  "Desenvolvimento de Sites": Code,
  "Desenvolvimento de Apps": Smartphone,
  "Suporte em TI": Headset,
  "Redes de Computadores": Network,
  "Marketing Digital": Megaphone,
  "Criação de Lojas Virtuais": ShoppingCart,
  "Hospedagem de Sites": Server,
  SEO: Search,
  "Gestão de Redes Sociais": Share2,
  "Tráfego Pago": TrendingUp,
  "Design Gráfico": PenTool,
  "Edição de Vídeo": Video,
  "Produção de Conteúdo": Camera,
  "Segurança Digital": Lock,
  "Consultoria em IA": Bot,
  Advogados: Scale,
  Contadores: Calculator,
  "Corretores de Imóveis": Home,
  "Consultores Financeiros": Landmark,
  Despachantes: FileText,
  Fotógrafos: Camera,
  Filmagens: Video,
  DJs: Headphones,
  Buffets: UtensilsCrossed,
  "Decoração de Festas": PartyPopper,
  "Organização de Eventos": CalendarCheck,
  Cerimonialistas: Heart,
  "Casas de Festas": PartyPopper,
  "Aluguel de Brinquedos": Sparkles,
  "Aluguel de Mesas e Cadeiras": Armchair,
  "Som e Iluminação": Lightbulb,
  "Cabines Fotográficas": Camera,
  "Segurança para Eventos": Shield,
  Garçons: UtensilsCrossed,
  Bartenders: Wine,
  "Recursos Humanos": Users,
  "Segurança do Trabalho": HardHat,
  "Consultoria Empresarial": Briefcase,
  "Cobrança e Recuperação": Banknote,
  "Terceirização de Serviços": Users,
  Motoboys: Truck,
  Transportadoras: Truck,
  Fretes: Truck,
  Táxis: Car,
  "Motoristas Particulares": Car,
  Academias: Dumbbell,
  "Personal Trainers": Dumbbell,
  Pilates: Activity,
  CrossFit: Dumbbell,
  Natação: Waves,
  "Artes Marciais": Swords,
  Yoga: Flower2,
  Dança: Music,
  "Treinamento Funcional": Activity,
  "Escolinhas de Futebol": Trophy,
  Imobiliárias: Home,
  "Avaliação de Imóveis": ClipboardCheck,
  "Administração de Condomínios": Building2,
  "Regularização de Imóveis": FileCheck,
  Topografia: Map,
  Arquitetura: PencilRuler,
  "Design de Interiores": Sofa,
  Paisagismo: TreePine,
  "Inspeção Predial": ClipboardCheck,
  "Financiamento Imobiliário": Landmark,
  "Energia Solar": Sun,
  "Instalação Elétrica": Zap,
  "Automação Residencial": Settings2,
  Geradores: BatteryCharging,
  "Poços Artesianos": Droplet,
  "Purificadores de Água": Droplets,
  "Instalação de Gás": Flame,
  "Aquecimento Solar": Sun,
  Climatização: Wind,
  Refrigeração: Snowflake,
  "Assistência Agrícola": Sprout,
  "Veterinários Rurais": PawPrint,
  Irrigação: Droplets,
  "Máquinas Agrícolas": Tractor,
  "Drones Agrícolas": Radar,
  Silagem: Package,
  "Cercamento Rural": Shield,
  "Consultoria Agronômica": Sprout,
  "Transporte de Gado": Truck,
  "Armazenagem Agrícola": Warehouse,
  "Soldagem Industrial": Flame,
  Usinagem: Cog,
  Caldeiraria: Flame,
  "Automação Industrial": Cpu,
  "Manutenção Industrial": Wrench,
  "Controle de Qualidade": ClipboardCheck,
  "Engenharia Mecânica": Cog,
  "Engenharia Elétrica": Zap,
  "Logística Industrial": Truck,
  "Segurança Industrial": HardHat,
  "Agências de Publicidade": Megaphone,
  "Comunicação Visual": Palette,
  Gráficas: Printer,
  "Impressão 3D": Box,
  "Produção Musical": Music,
  "Estúdios de Gravação": Mic,
  Locução: Mic,
  Ilustração: PenTool,
  "Fotografia Comercial": Camera,
  "Produção Audiovisual": Video,
  Babás: Baby,
  "Cuidadores de Idosos": HeartHandshake,
  "Acompanhantes Hospitalares": HeartHandshake,
  "Recreação Infantil": Gamepad2,
  "Orientação Familiar": Users,
  "Aulas para Crianças": BookOpen,
  "Transporte Escolar": Bus,
  "Casas de Repouso": Home,
  Berçários: Baby,
  "Monitoria Escolar": BookOpen,
  "Vigilância Patrimonial": Shield,
  Portaria: DoorOpen,
  "Monitoramento 24h": Eye,
  Escolta: ShieldCheck,
  "Investigação Particular": Search,
  "Segurança Eletrônica": Lock,
  Alarmes: Siren,
  "Controle de Acesso": KeyRound,
  "Portões Automáticos": DoorClosed,
  "Segurança Empresarial": ShieldCheck,
  "Correspondente Bancário": Landmark,
  Seguros: ShieldCheck,
  Consórcios: Coins,
  "Planejamento Financeiro": Calculator,
  "Recuperação de Crédito": Banknote,
  Investimentos: TrendingUp,
  Financiamentos: Banknote,
  Câmbio: ArrowLeftRight,
  "Crédito Rural": Sprout,
  "Crédito Imobiliário": Home,
  "Direito Trabalhista": Scale,
  "Direito Previdenciário": Scale,
  "Direito Civil": Scale,
  "Direito Criminal": Gavel,
  "Direito Empresarial": Briefcase,
  "Direito Imobiliário": Home,
  "Direito Tributário": Calculator,
  Mediação: Handshake,
  Arbitragem: Gavel,
  "Assessoria Jurídica": Scale,
  "Representação Comercial": Briefcase,
  Franquias: Store,
  Distribuidoras: Truck,
  Importação: Ship,
  Exportação: Ship,
  "E-commerce": ShoppingCart,
  Marketplace: Store,
  "Pesquisa de Mercado": Search,
  Auditoria: ClipboardCheck,
  Compliance: ShieldCheck,
  "Entregas Expressas": Truck,
  Armazenagem: Warehouse,
  "Centros de Distribuição": Warehouse,
  "Transporte Refrigerado": Snowflake,
  "Logística Reversa": RotateCcw,
  Courier: Bike,
  "Mudanças Interestaduais": Truck,
  "Frete Pesado": Truck,
  "Transporte Executivo": Car,
  "Licenciamento Ambiental": FileCheck,
  "Gestão de Resíduos": Trash2,
  "Coleta Seletiva": Recycle,
  Reciclagem: Recycle,
  "Consultoria Ambiental": Leaf,
  "Recuperação de Áreas": TreePine,
  "Educação Ambiental": Leaf,
  "Análises Ambientais": FlaskConical,
  "Tratamento de Água": Droplets,
  "Tratamento de Esgoto": Droplets,
  Tradução: Languages,
  Intérprete: Languages,
  Coaching: Target,
  Mentoria: Users,
  "Recrutamento e Seleção": Users,
  "Pesquisa Particular": Search,
  "Digitalização de Documentos": ScanLine,
  "Certificação Digital": BadgeCheck,
  "Despachante Documental": FileText,
  Leiloeiros: Gavel,
  "Perícias Técnicas": Search,
  "Avaliação de Bens": ClipboardCheck,
  "Consultoria Estratégica": Target,
  "Atendimento Virtual": Headset,
  "Outros Serviços": Briefcase,
  "Venda de Tratores": Tractor,
  "Aluguel de Tratores": Tractor,
  "Manutenção de Tratores": Wrench,
  "Revisão de Tratores": Wrench,
  "Peças para Tratores": Cog,
  "Tratores de Esteira": Tractor,
  "Implementos Agrícolas": Cog,
  Colheitadeiras: Tractor,
  "Manutenção de Colheitadeiras": Wrench,
  Plantadeiras: Sprout,
  "Manutenção de Plantadeiras": Wrench,
  "Pulverizadores Agrícolas": Droplets,
  "Pulverização Aérea": Plane,
  "Roçadeiras Agrícolas": Sprout,
  "Grades Agrícolas": Cog,
  Arados: Cog,
  Subsoladores: Cog,
  "Carretas Agrícolas": Truck,
  "Pá Carregadeira": Construction,
  Retroescavadeira: Construction,
  "Escavadeira Hidráulica": Construction,
  Motoniveladora: Construction,
  "Rolo Compactador": Construction,
  Guindastes: Construction,
  Munck: Truck,
  Empilhadeiras: Boxes,
  "Manutenção de Máquinas Pesadas": Wrench,
  "Aluguel de Máquinas Pesadas": Construction,
  "Venda de Máquinas Pesadas": Construction,
  "Peças para Máquinas Pesadas": Cog,
  "Pneus para Máquinas Agrícolas": Disc,
  "Hidráulica Industrial": Droplet,
  "Solda para Máquinas Agrícolas": Flame,
  "Usinagem de Peças Agrícolas": Cog,
  "Revisão de Motores Diesel": Wrench,
  "Injeção Eletrônica Diesel": Zap,
  "Turbina Diesel": Wind,
  "Transporte de Máquinas Pesadas": Truck,
  "Guincho para Máquinas Pesadas": Truck,
  "Operador de Máquinas Pesadas": HardHat,
  "Locação de Operadores Agrícolas": Users,
  Terraplanagem: Construction,
  "Nivelamento de Terreno": Construction,
  Escavação: Construction,
  "Demolição com Máquinas": Construction,
  Britagem: Cog,
  "Perfuração de Poços": Droplet,
  "Irrigação por Pivô": Droplets,
  "Construção de Silos": Warehouse,
  "Funilaria de Máquinas Agrícolas": Hammer,
  "Pintura de Máquinas Agrícolas": SprayCan,
  "Diagnóstico Eletrônico de Máquinas": Cpu,
  "Aluguel de Caçambas": Truck,
  "Aluguel de Compressores Industriais": Wind,
  "Locação de Equipamentos para Construção": HardHat,
  "Manutenção de Retroescavadeiras": Wrench,
  "Manutenção de Escavadeiras": Wrench,
  "Reforma de Tratores": Tractor,
  "Comércio de Peças Agrícolas": Cog,
  "Assistência Técnica para Tratores": Wrench,
};

/** Lista plana com todos os nomes de categoria (sem grupo). */
export const SERVICE_CATEGORIES: string[] = SERVICE_CATEGORY_GROUPS.flatMap(
  (g) => g.items,
);

/** Mapeia os 8 valores antigos do enum fechado pro nome de texto livre equivalente. */
export const LEGACY_SERVICE_TYPE_MAP: Record<string, string> = {
  academia: "Academias",
  dentista: "Dentistas",
  farmacia: "Farmácias",
  advogado: "Advogados",
  mecanico: "Oficinas Mecânicas",
  salao: "Salões de Beleza",
  clinica: "Clínicas Médicas",
  outro: "Outros Serviços",
};

/** Resolve o texto de exibição de uma categoria, incluindo valores antigos do enum. */
export function resolveServiceTypeLabel(
  value: string | null | undefined,
): string {
  if (!value) return "Serviço";
  return LEGACY_SERVICE_TYPE_MAP[value] || value;
}

/** Resolve o ícone do grupo (setor) de uma categoria, com fallback genérico. */
export function resolveServiceTypeIcon(
  value: string | null | undefined,
): LucideIcon {
  const label = resolveServiceTypeLabel(value);
  if (SERVICE_ITEM_ICONS[label]) return SERVICE_ITEM_ICONS[label];
  return (
    SERVICE_CATEGORY_GROUPS.find((g) => g.items.includes(label))?.icon ||
    Briefcase
  );
}
