export const PRODUCT_CATEGORIES = [
  "Abajures e Luminárias",
  "Acessórios de Câmeras",
  "Acessórios de Celular",
  "Acessórios de Computador",
  "Acessórios de Informática",
  "Acessórios de Inverno",
  "Acessórios de Moda Feminina",
  "Acessórios de Moda Masculina",
  "Acessórios de Moto",
  "Acessórios de Viagem",
  "Acessórios de Áudio",
  "Acessórios para Animais",
  "Acessórios para Banheiro",
  "Acessórios para Cama e Mesa",
  "Acessórios para Caminhões",
  "Acessórios para Carros",
  "Acessórios para Ciclismo",
  "Acessórios para Consoles",
  "Acessórios para Costura",
  "Acessórios para Decoração",
  "Acessórios para Drones",
  "Acessórios para Eletrodomésticos",
  "Acessórios para Esportes",
  "Acessórios para Ferramentas",
  "Acessórios para Ginástica",
  "Acessórios para Gatos",
  "Acessórios para Instrumentos Musicais",
  "Acessórios para Jardim",
  "Acessórios para Lojas",
  "Acessórios para Máquinas Agrícolas",
  "Acessórios para Náutica",
  "Acessórios para Notebooks",
  "Acessórios para Papelaria",
  "Acessórios para Pesca",
  "Acessórios para Piscinas",
  "Acessórios para Smartwatches",
  "Acessórios para Tablets",
  "Acessórios para Tatuagem",
  "Acessórios para Vinho",
  "Acabamento para Construção",
  "Açougue e Carnes",
  "Aeronaves e Peças",
  "Afiadores e Amoladores",
  "Agendas e Planners",
  "Agro e Indústria",
  "Alarme e Segurança",
  "Alianças de Casamento e Noivado",
  "Alimentos Funcionais",
  "Alimentos Infantis",
  "Alimentos para Animais",
  "Alimentos para Cães",
  "Alimentos para Gatos",
  "Alimentos Sem Glúten",
  "Alimentos Veganos",
  "Alto-falantes",
  "Amortecedores",
  "Anéis",
  "Animações e Desenhos",
  "Animais de Grande Porte",
  "Animais de Produção",
  "Antenas e Receptores",
  "Antiguidades",
  "Antiguidades Asiáticas",
  "Aparelhos Auditivos",
  "Aparelhos de Barbear",
  "Aparelhos de Depilação",
  "Aparelhos de Fondue",
  "Aparelhos de Jantar",
  "Aparelhos de Som",
  "Aparelhos Ortopédicos",
  "Apostas e Jogos",
  "Apostilas e Cursos",
  "Aquários e Acessórios",
  "Aquecedores de Água",
  "Aquecedores de Ambiente",
  "Ar Condicionado",
  "Armações de Óculos",
  "Armadilhas e Repelentes",
  "Armários e Guarda-Roupas",
  "Arte Digital",
  "Arte, Papelaria e Armarinho",
  "Artes Marciais",
  "Artigos de Caça",
  "Artigos de Festas",
  "Artigos de Natal",
  "Artigos Esotéricos",
  "Artigos Esportivos",
  "Artigos Infantis",
  "Artigos para Artesanato",
  "Artigos para Bebês",
  "Artigos para Confeitaria",
  "Artigos para Costura",
  "Artigos Religiosos",
  "Asfalto e Pavimentação",
  "Aspiradores de Pó",
  "Aulas e Cursos",
  "Automodelismo",
  "Aves",
  "Balas e Doces",
  "Balanças",
  "Balcões e Vitrines",
  "Banheiras e Ofurôs",
  "Banheiro",
  "Barbantes e Fios",
  "Barcos e Lanchas",
  "Barracas de Camping",
  "Basquete",
  "Batedeiras",
  "Baterias Automotivas",
  "Baterias e Carregadores",
  "Baterias Musicais",
  "Bebedouros e Purificadores",
  "Bebês",
  "Bebês Conforto",
  "Bebidas Alcoólicas",
  "Bebidas Não Alcoólicas",
  "Bermudas e Shorts Femininos",
  "Bermudas e Shorts Masculinos",
  "Berços e Cercados",
  "Bicicletas",
  "Bicicletas Elétricas",
  "Bijuterias",
  "Binóculos e Telescópios",
  "Biquínis e Maiôs",
  "Biscoitos e Bolachas",
  "Bistequeiras e Grelhas",
  "Blocos de Montar",
  "Blu-Ray e DVDs",
  "Bóias e Infláveis",
  "Bolas Esportivas",
  "Bolos e Tortas",
  "Bolsas Femininas",
  "Bolsas Masculinas",
  "Bolsas Maternidade",
  "Bombas de Água",
  "Bonecas",
  "Bonecos de Ação",
  "Bonés e Chapéus",
  "Botas e Coturnos",
  "Box para Banheiro",
  "Braceletes",
  "Brindes Personalizados",
  "Brincos",
  "Brinquedos de Controle Remoto",
  "Brinquedos de Pegadinha",
  "Brinquedos Educativos",
  "Brinquedos Musicais",
  "Brinquedos para Bebês",
  "Brinquedos para Cachorros",
  "Brinquedos para Gatos",
  "Cabides e Araras",
  "Cabos de Áudio e Vídeo",
  "Cabos e Adaptadores",
  "Cabos de Energia",
  "Cachorros",
  "Cadeados e Fechaduras",
  "Cadeiras de Alimentação",
  "Cadeiras de Banho",
  "Cadeiras de Escritório",
  "Cadeiras de Praia",
  "Cadeiras e Poltronas",
  "Cadeiras Gamer",
  "Cadeiras para Auto",
  "Cadernos e Fichários",
  "Café e Moedores",
  "Cafeteiras",
  "Caixas de Som",
  "Caixas Organizadoras",
  "Calçados Esportivos",
  "Calçados Femininos",
  "Calçados Infantis",
  "Calçados Masculinos",
  "Calças Femininas",
  "Calças Masculinas",
  "Cálcio e Vitaminas",
  "Calculadoras",
  "Camas e Colchões",
  "Câmeras Analógicas",
  "Câmeras de Ação",
  "Câmeras de Segurança",
  "Câmeras Digitais",
  "Câmeras e Filmagens",
  "Camisas de Time",
  "Camisas Masculinas",
  "Camisetas Femininas",
  "Camisetas Masculinas",
  "Camping e Pesca",
  "Canetas e Lápis",
  "Capacetes Automotivos",
  "Capacetes de Moto",
  "Capas de Chuva",
  "Capas para Carros",
  "Capas para Celular",
  "Capas para Notebook",
  "Capas para Tablet",
  "Cardiologia e Medição",
  "Carne de Aves",
  "Carne Suína e Bovina",
  "Carrinhos de Bebê",
  "Carrinhos de Coleção",
  "Carrinhos de Controle Remoto",
  "Cartões de Memória",
  "Cartuchos e Toners",
  "Casacos e Jaquetas",
  "Cases e Bags Musicais",
  "Catálogos e Manuais",
  "Cavalgada e Hipismo",
  "Cavalos e Equinos",
  "CDs e Discos de Vinil",
  "Cédulas e Moedas Antigas",
  "Celulares e Smartphones",
  "Cerâmica e Porcelana",
  "Cercas e Telas",
  "Cervejas Artesanais",
  "Cervejas Industriais",
  "Cestas Básicas",
  "Cestas de Café da Manhã",
  "Chaleiras e Bules",
  "Chapas e Lanches",
  "Chaves e Ferramentas Manuais",
  "Chocolates e Bombons",
  "Chopeiras",
  "Chupetas e Mordedores",
  "Churrasqueiras",
  "Chuveiros e Duchas",
  "Ciclismo",
  "Cílios Postiços",
  "Cintos",
  "Cobertores e Mantas",
  "Cofres",
  "Coifas e Depuradores",
  "Colares e Correntes",
  "Colchões",
  "Coleções e Hobbies",
  "Colunas e Torres de Som",
  "Comics e Mangás",
  "Componentes de PC",
  "Componentes Eletrônicos",
  "Compressores de Ar",
  "Computadores All-in-One",
  "Computadores de Mesa",
  "Conectores e Terminais",
  "Conjuntos Infantis",
  "Console Nintendo",
  "Console PlayStation",
  "Console Xbox",
  "Consoles Antigos",
  "Consoles Portáteis",
  "Construção Civil",
  "Consultoria e Assessoria",
  "Contatores e Relés",
  "Controles de Acesso",
  "Controles para Videogame",
  "Convites e Lembrancinhas",
  "Copos e Taças",
  "Coroas e Tiaras",
  "Corpetes e Corsets",
  "Corridas e Maratonas",
  "Cortadores de Grama",
  "Cortinas e Persianas",
  "Cosméticos e Skincare",
  "Costura e Bordado",
  "Couro e Sintéticos",
  "Cozinhas Compactas",
  "Cremes Antissinais",
  "Cremes Hidratantes",
  "Cristais e Pedras",
  "Cromos e Figurinhas",
  "Cuidado Corporal",
  "Cuidado Facial",
  "Cuidados com a Pele",
  "Cuidados Íntimos",
  "Cursos de Idiomas",
  "Cursos Profissionalizantes",
  "Danças e Ballet",
  "Decoração de Festas",
  "Decoração de Interiores",
  "Decoração de Jardim",
  "Decoração Natalina",
  "Demaquilantes",
  "Depilação a Laser",
  "Depilação Cera",
  "Descansos de Panela",
  "Design e Criação",
  "Desktops e PCs",
  "Desodorantes",
  "Dietas e Emagrecimento",
  "Discos de Freio",
  "Discos Rígidos (HD)",
  "Disjuntores",
  "Display e Telas",
  "Diy e Bricolagem",
  "Doces Caseiros",
  "Doces e Sobremesas",
  "Drones",
  "Edredons e Cobre-leitos",
  "Eletrodomésticos",
  "Eletroportáteis",
  "Embalagens para Festas",
  "Embalagens para Presentes",
  "Encanamento e Hidráulica",
  "Energia Solar",
  "Equipamentos de DJ",
  "Equipamentos Médicos",
  "Equipamentos Odontológicos",
  "Equipamentos para Academia",
  "Equipamentos para Gastronomia",
  "Equipamentos para Supermercados",
  "Escadas",
  "Escapamentos",
  "Esmaltes e Unhas",
  "Espelhos",
  "Esportes Aquáticos",
  "Esportes de Inverno",
  "Esportes de Quadra",
  "Espumantes",
  "Estantes e Racks",
  "Esteiras Ergométricas",
  "Estetoscópios",
  "Estofados e Sofás",
  "Estúdios e Gravação",
  "E-readers e Kindles",
  "Exaustores",
  "Extensões e Filtros de Linha",
  "Faqueiros e Talheres",
  "Faróis e Lanternas Automotivas",
  "Fantasias",
  "Farinhas e Grãos",
  "Ferramentas de Medição",
  "Ferramentas Elétricas",
  "Ferramentas Manuais",
  "Ferramentas Pneumáticas",
  "Ferragens",
  "Ferro e Aço",
  "Ferros de Passar",
  "Fertilizantes e Adubos",
  "Filamentos para Impressão 3D",
  "Filatelia (Selos)",
  "Filtros de Água",
  "Filtros de Ar Automotivos",
  "Filtros Fotográficos",
  "Fios e Cabos Elétricos",
  "Fitas Adesivas e Isolantes",
  "Fitas LED",
  "Fitas VHS e Cassetes",
  "Fitness e Musculação",
  "Flash e Iluminação de Estúdio",
  "Fliperamas e Arcades",
  "Flores e Plantas Artificiais",
  "Flores Naturais",
  "Fogões e Fornos",
  "Fones de Ouvido",
  "Fontes de Alimentação",
  "Fotografia e Câmeras",
  "Fragrâncias e Perfumes",
  "Fraldas Descartáveis",
  "Frascos e Potes",
  "Freezers",
  "Freios Automotivos",
  "Fritadeiras Elétricas (Airfryer)",
  "Frutas Frescas",
  "Furadeiras e Parafusadeiras",
  "Futebol",
  "Futmesa e Pebolim",
  "Gaiolas e Viveiros",
  "Games e Videogames",
  "Garrafas Térmicas",
  "Gatos",
  "Geladeiras e Refrigeradores",
  "Geleias e Pastas",
  "Gelo e Bebidas Geladas",
  "Geradores de Energia",
  "Ginástica Rítmica e Artística",
  "Gin, Vodka e Destilados",
  "Golfe",
  "Gorro e Cachecol",
  "GPS Automotivo",
  "GPS e Monitores Esportivos",
  "Gráfica e Impressão",
  "Gravatas",
  "Grills e Sanduicheiras",
  "Guarda-Chuvas",
  "Guarda-Sóis e Tendas",
  "Guitarras e Baixos",
  "Halts e Anilhas",
  "Handebol",
  "Hardwares de Rede",
  "Hidratação Capilar",
  "Higiene Bucal",
  "Higiene e Banho de Bebês",
  "Higiene Íntima",
  "Higiene Pessoal",
  "Home Theaters",
  "Hortaliças e Verduras",
  "Hortifruti",
  "Iluminação de Interiores",
  "Iluminação Externa",
  "Iluminação Pública",
  "Ilhas e Bancadas",
  "Impressoras e Multifuncionais",
  "Impressoras 3D",
  "Inaladores e Nebulizadores",
  "Incensos e Velas Aromáticas",
  "Indumentária Gaúcha",
  "Infraestrutura de Redes",
  "Ingressos e Eventos",
  "Instrumentos de Corda",
  "Instrumentos de Percussão",
  "Instrumentos de Sopro",
  "Instrumentos Musicais Infantis",
  "Insumos Agrícolas",
  "Interruptores e Tomadas",
  "Investigações e Espionagem",
  "Iscas Artificiais",
  "Isqueiros e Charutos",
  "Itens Colecionáveis",
  "Jaquetas de Couro",
  "Jaquetas e Moletons",
  "Jardim e Área Externa",
  "Jeans",
  "Jogos de Cartas",
  "Jogos de Computador",
  "Jogos de Tabuleiro",
  "Jogos para PS4",
  "Jogos para PS5",
  "Jogos para Xbox",
  "Jogos para Nintendo",
  "Joias em Ouro",
  "Joias em Prata",
  "Kimônos",
  "Kit Berço",
  "Kit Churrasco",
  "Lâmpadas de LED",
  "Lâmpadas Inteligentes",
  "Lanchas e Jet Skis",
  "Lancheiras Infantis",
  "Lápis de Cor e Tintas",
  "Lareiras",
  "Laticínios e Frios",
  "Lavadoras de Alta Pressão",
  "Lavadoras de Roupas",
  "Lembrancinhas de Casamento",
  "Lembrancinhas de Maternidade",
  "Lenços e Echarpes",
  "Lentes de Contato",
  "Lentes para Câmeras",
  "Licenças de Software",
  "Licores",
  "Lingeries",
  "Linhas de Pesca",
  "Lixeiras",
  "Livros de Administração",
  "Livros de Arte",
  "Livros de Concurso",
  "Livros de Direito",
  "Livros de Exatas",
  "Livros de Ficção",
  "Livros de Idiomas",
  "Livros de Literatura",
  "Livros de Medicina",
  "Livros de Religião",
  "Livros Didáticos",
  "Livros e Revistas",
  "Lonas e Coberturas",
  "Louças de Banheiro",
  "Lubrificantes Automotivos",
  "Luminárias",
  "Luvas Esportivas",
  "Maçanetas e Puxadores",
  "Macarrão e Massas",
  "Máquinas Agrícolas",
  "Máquinas de Café Expresso",
  "Máquinas de Costura",
  "Máquinas de Lavar Louça",
  "Máquinas de Solda",
  "Máquinas Industriais",
  "Malas de Viagem",
  "Manequins e Expositores",
  "Mangueiras e Irrigação",
  "Manutenção e Consertos",
  "Maquetes",
  "Maquiagem para Boca",
  "Maquiagem para Olhos",
  "Maquiagem para Rosto",
  "Marchetaria",
  "Marcenaria e Madeiras",
  "Massageadores",
  "Massas e Argamassas",
  "Materiais de Construção",
  "Materiais de Escritório",
  "Materiais Escolares",
  "Mecânica Automotiva",
  "Medicina Alternativa",
  "Meias",
  "Memórias RAM",
  "Mesas de Bilhar e Sinuca",
  "Mesas de Centro",
  "Mesas de Jantar",
  "Mesas e Cadeiras",
  "Mergulho",
  "Microfones",
  "Micro-ondas",
  "Micros e Mini System",
  "Microscópios",
  "Miniaturas de Carros",
  "Misturadores de Água",
  "Mochilas Escolares",
  "Mochilas Esportivas",
  "Modeladores de Cabelo",
  "Modems e Roteadores",
  "Molduras e Quadros",
  "Moleskines e Cadernos Premium",
  "Monitores",
  "Monitores de Estúdio",
  "Motocicletas e Quadriciclos",
  "Motores Automotivos",
  "Motores de Popa",
  "Mouses",
  "Mousepads",
  "Móveis Antigos",
  "Móveis de Aço",
  "Móveis para Banheiro",
  "Móveis para Cozinha",
  "Móveis para Escritório",
  "Móveis para Quarto",
  "Móveis para Sala",
  "Mudas de Plantas",
  "Multifuncionais a Laser",
  "Música Digital",
  "Narguilés e Acessórios",
  "Natação",
  "Nobreaks e Estabilizadores",
  "Notebooks",
  "Numismática",
  "Nutrição Esportiva",
  "Obras de Arte",
  "Óculos de Grau",
  "Óculos de Sol",
  "Óleos Essenciais",
  "Ombrelones",
  "Organização Doméstica",
  "Outras Categorias",
  "Órgãos Eletrônicos",
  "Ortopedia",
  "Pães e Bolos",
  "Painéis de TV",
  "Painéis Solares",
  "Paineis Fotográficos",
  "Palmilhas",
  "Panelas e Frigideiras",
  "Panificação Industrial",
  "Papas e Ração para Pássaros",
  "Papel Higiênico",
  "Papel Parede",
  "Papéis para Impressão",
  "Parafusos e Buchas",
  "Para-choques",
  "Pássaros e Aves",
  "Pasta de Amendoim",
  "Pastilhas de Freio",
  "Patinetes e Scooters",
  "Patins e Skate",
  "Paus de Selfie e Gimbal",
  "Pçs e Componentes Agrícolas",
  "PDVs e Caixas Registradoras",
  "Peças de Carros",
  "Peças de Motos",
  "Peças de Caminhões",
  "Pedais de Efeito para Guitarra",
  "Pedais de Bateria",
  "Pedrarias e Strass",
  "Peixaria",
  "Peixes de Aquário",
  "Películas para Celular",
  "Pelúcias",
  "Pen Drives",
  "Pentes e Escovas",
  "Perfumes Femininos",
  "Perfumes Masculinos",
  "Pesca Esportiva",
  "Pesticidas e Herbicidas",
  "Piano Acústico",
  "Piano Digital",
  "Pijamas",
  "Pincéis de Maquiagem",
  "Pinturas e Telas",
  "Piscinas",
  "Pisos e Revestimentos",
  "Pistas de Autorama",
  "Pizzas e Congelados",
  "Placas de Captura",
  "Placas de Som",
  "Placas de Vídeo",
  "Placas Mãe",
  "Plantas Artificiais",
  "Pneus de Carro",
  "Pneus de Moto",
  "Podcasts e Estúdios",
  "Poltronas Decorativas",
  "Portas e Janelas",
  "Porcelanatos",
  "Pósteres",
  "Pranchas de Surf",
  "Pranchas de Cabelo",
  "Prataria e Metais Antigos",
  "Pratos e Tigelas",
  "Prensas Térmicas",
  "Presentes Criativos",
  "Previdência e Seguros",
  "Processadores (CPU)",
  "Processadores de Alimentos",
  "Projetores",
  "Proteção de Moto",
  "Próteses",
  "Produtos de Limpeza",
  "Produtos Naturais",
  "Produtos Veganos",
  "Pulseiras",
  "Quadriciclos",
  "Quadros Decorativos",
  "Quebra-Cabeças",
  "Queijos",
  "Rações",
  "Radiadores",
  "Rádios Comunicadores",
  "Rádios Portáteis",
  "Rastreamento de Veículos",
  "Redes de Descanso",
  "Refletores",
  "Regatas",
  "Relógios de Bolso",
  "Relógios de Parede",
  "Relógios Inteligentes (Smartwatch)",
  "Relógios Masculinos",
  "Relógios Femininos",
  "Répteis e Anfíbios",
  "Retrovisores",
  "Revistas em Quadrinhos (HQs)",
  "Revistas e Periódicos",
  "Rodas e Calotas",
  "Roedores",
  "Roupas de Bebê",
  "Roupas de Cama",
  "Roupas de Chuva",
  "Roupas Esportivas",
  "Roupas Íntimas",
  "Roupas Sociais",
  "Roteadores e Repetidores",
  "Sabonetes e Loções",
  "Sacos de Dormir",
  "Saias",
  "Sais de Banho",
  "Saltos e Scarpins",
  "Salões e Barbearias",
  "Sandálias e Rasteiras",
  "Sanduicheiras",
  "Sapatilhas",
  "Sapatos Masculinos",
  "Saúde e Bem Estar",
  "Secadoras de Roupa",
  "Secadores de Cabelo",
  "Sementes",
  "Sensor de Ré",
  "Serras",
  "Servidores e Storage",
  "Serviços Automotivos",
  "Serviços de Informática",
  "Serviços Domésticos",
  "Serviços Gráficos",
  "Sex Shop",
  "Shampoos e Condicionadores",
  "Shorts",
  "Skate e Longboard",
  "Snacks e Salgadinhos",
  "Softwares e Programas",
  "Sogas e Cintos Regionais",
  "Solda e Inversoras",
  "Sombreadores e Telas Agrícolas",
  "Somieres e Base Cama",
  "Sons Automotivos",
  "Sorvetes e Picolés",
  "Squash",
  "Sucatas e Peças",
  "Suculentas e Cactos",
  "Sucos e Polpas",
  "Suéteres e Tricôs",
  "Suplementos Alimentares",
  "Suportes para TV",
  "Surf e Bodyboard",
  "Tablets",
  "Tacos de Beisebol",
  "Tapetes de Automóveis",
  "Tapetes e Capachos",
  "Taças e Copos Especias",
  "Teatros e Fantoches",
  "Teclados Musicais",
  "Teclados para Computador",
  "Tecnologia Assistiva",
  "Telefones com Fio",
  "Telefones Sem Fio",
  "Telescópios",
  "Televisões (TVs)",
  "Temperos e Condimentos",
  "Tênis Casual",
  "Tênis de Corrida",
  "Tênis de Mesa",
  "Tênis Esportivo",
  "Tendas e Gazebos",
  "Ternos e Gravatas",
  "Termômetros",
  "Tigelas e Vasilhas",
  "Tintas e Pincéis",
  "Toalhas de Banho",
  "Toalhas de Mesa",
  "Toca Discos",
  "Toldos",
  "Toldos e Coberturas",
  "Torneiras",
  "Torradeiras",
  "Tortas Doces e Salgadas",
  "Toucadores e Penteadeiras",
  "Tratores e Implementos",
  "Travesseiros",
  "Tripés e Suportes",
  "Trompetes e Metais",
  "Tubos e Conexões",
  "Umidificadores de Ar",
  "Utensílios de Cozinha",
  "Vans e Perua",
  "Vaporizadores e Passadeiras",
  "Varões e Acessórios",
  "Vasos e Floreiras",
  "Veículos Pesados",
  "Velas e Parafinas",
  "Veleiros e Botes",
  "Ventiladores e Circuladores",
  "Verduras Frescas",
  "Vestidos de Festa",
  "Vestidos e Túnicas",
  "Vestuário para Animais",
  "Veterinária e Saúde Animal",
  "Videogames Consoles",
  "Videogames Jogos",
  "Vinhos e Espumantes",
  "Violões e Violas",
  "Violinos e Arcos",
  "Violoncelos",
  "Vitrines e Expositores",
  "Vodka",
  "Vôlei",
  "Webcams",
  "Whisky",
  "Windsurf e Kitesurf",
  "Woks e Panelas Especiais",
  "Xícaras e Canecas",
  // ── Produtos Digitais ──
  "📥 eBooks e Livros Digitais",
  "📥 Softwares e Aplicativos",
  "📥 Planilhas e Templates",
  "📥 Cursos Online e Videoaulas",
  "📥 Músicas e Áudios Digitais",
  "📥 Artes e Designs Gráficos",
  "📥 Plugins e Extensões",
  "📥 Presets e Filtros",
  "📥 Apostilas e PDFs",
  "📥 Fontes Tipográficas",
  "📥 Modelos 3D",
  "📥 Jogos Digitais (PC/Mobile)",
  "📥 Scripts e Código-Fonte",
  "📥 Receitas e Guias Digitais",
  "📥 Outros Produtos Digitais"
].sort((a, b) => a.localeCompare(b, 'pt-BR'));
