-- =====================================================================
-- CATEGORIAS LOJA — Inserir 272 novas categorias (ordem alfabetica)
-- Total final: 300 (28 existentes + 272 novas)
-- =====================================================================

-- Passo 1: Limpar categorias desta lista (caso tentativa anterior tenha inserido parcialmente)
-- NAO apaga as 28 originais, so as novas desta lista
DELETE FROM public.categorias_loja WHERE nome IN (
'Acabamentos','Acessorios Automotivos','Acessorios Femininos','Acessorios Masculinos','Acougue','Acupuntura','Adestramento','Advocacia','Agua e Gelo','Agropecuaria','Alfaiataria','Alimentos Congelados','Alimentos Fitness','Alimentos Funcionais','Alimentos Importados','Alimentos Naturais','Alimentos Sem Gluten','Alimentos Sem Lactose','Alimentos Veganos','Antenas e Receptores','Aquarismo','Aquecedores','Ar Condicionado','Armas e Municao','Aromaterapia','Arquitetura','Artigos de Pesca','Artigos Esportivos','Assessoria Contabil','Assessoria de Marketing','Assistencia Tecnica','Audio e Som','Aulas de Musica','Aulas Particulares','Auto Eletrica','Auto Escola','Auto Pecas','Automacao Residencial','Aventura e Ecoturismo','Balas e Doces','Banho e Tosa','Banheiros e Metais','Baterias e Carregadores','Biblioteca','Bicicletas','Bijuterias','Biscoitos e Bolachas','Blindagem','Bolos e Tortas','Bolsas e Carteiras','Bone e Chapeus','Borracharia','Brinquedoteca','Cabos e Adaptadores','Cafeteria','Calcados Esportivos','Calcados Femininos','Calcados Infantis','Calcados Masculinos','Cameras e Filmadoras','Caminhoes','Camping','Camisetas Personalizadas','Cannabis Medicinal','Capoeira','Carnes e Embutidos','Carpintaria','Cartorio','Casa de Festas','Casa de Sucos','Ceramicas e Azulejos','Cervejaria Artesanal','Chocolates','Churrasqueiras','Cirurgia Plastica','Clinica Dentaria','Clinica Dermatologica','Clinica Estetica','Clinica Medica','Clinica Oftalmologica','Clinica Veterinaria','Clube Recreativo','Coaching','Coaching de Saude','Colchoes','Colesterol e Diabetes','Comida Arabe','Comida Chinesa','Comida Indiana','Comida Italiana','Comida Mexicana','Comida Nordestina','Comida Portuguesa','Comida Tailandesa','Componentes Eletronicos','Computadores','Concessionaria','Confeitaria','Conservas e Enlatados','Consoles e Videogames','Consultoria Empresarial','Contabilidade','Cortinas e Persianas','Cosmeticos Naturais','Coworking','Creperia','Criacao de Aves','Criacao de Peixes','Crossfit','Cursos Online','Cursos Profissionalizantes','Cursos Tecnicos','Customizacao Veicular','Danca','Decoracao de Festas','Delicatessen','Dermocosmeticos','Design Grafico','Desinsetizacao','Despachante','Despachante Aduaneiro','Distribuidora de Bebidas','Drogaria','Drones','Educacao Especial','Eletricista','Emporio','Encanamento','Engenharia','Envelopamento','Enxoval de Bebe','Equipamentos de Mergulho','Equipamentos de Rede','Equipamentos Hospitalares','Equipamentos Ortopedicos','Equinos','Ervas e Especiarias','Escalada','Escola de Artes','Escola de Culinaria','Escola de Esportes','Escola de Idiomas','Escola de Natacao','Escola Infantil','Escapamentos','Escritorio de Advocacia','Estacionamento','Estamparia','Estetica Automotiva','Estetica Capilar','Estetica Facial','Eventos e Producao','Faculdade','Ferragens','Fisioterapia','Flores e Plantas','Fones de Ouvido','Food Truck','Fotografia','Frios e Laticinios','Frutas e Verduras','Funilaria e Pintura','Futebol','Golfe','GPS e Navegacao','Grafica e Impressao','Graos e Cereais','Hamburgueria','HD e Armazenamento','Homeopatia','Hortifruti','Hospedagem Pet','Iluminacao LED','Imobiliaria','Impressoras','Ingles','Insumos Agricolas','Insulfilm','Iogurteria','Jardinagem','Joalheria','Kart','Laboratorio de Analises','Laboratorio de Informatica','Lava Rapido','Limpeza Profissional','Lingerie','Livraria','Locacao de Equipamentos','Locacao de Veiculos','Logistica','Loucas e Talheres','Lubrificantes','Lustres e Luminarias','Lutas e Artes Marciais','Madeiras','Manipulacao','Maquinas Agricolas','Marcenaria','Massoterapia','Material de Construcao','Material Eletrico','Material Escolar','Material Hidraulico','Mecanica Diesel','Mecanica Geral','Meditacao e Yoga','Meias e Pijamas','Moda Country','Moda Evangelica','Moda Feminina','Moda Fitness','Moda Infantil','Moda Intima','Moda Masculina','Moda Plus Size','Moda Praia','Moda Streetwear','Moda Sustentavel','Monitores','Motocicletas','Moveis de Escritorio','Moveis Planejados','Moveis Rusticos','Mudancas e Fretes','Museu','Nautica e Barcos','Notebooks','Nutricao','Oculos de Sol','Organizacao e Armazenamento','Otica','Paintball','Paisagismo','Papel de Parede','Papelaria','Parque de Diversoes','Patins e Skate','Pecas para PC','Perfumaria','Perifericos','Pet Food','Pet Shop','Pilates','Pintura e Acabamento','Piscinas','Pneus','Portas e Janelas','Pre-Vestibular','Producao de Video','Produtos Hospitalares','Produtos Ortopedicos','Projetores','Protese Dentaria','Psicologia','Publicidade','Quadras Esportivas','Quiropraxia','Racao e Nutricao Animal','Radiologia','Rafting','Rastreamento Veicular','Reboque e Guincho','Recursos Humanos','Reformas e Obras','Relogio Smartwatch','Relogios','Reparos de Celular','Retifica de Motores','Robotica','Rodas e Aros','Roupas de Cama','Roupas de Inverno','Roupas Esportivas','Roupas Sociais','Salao de Beleza','Sapataria','Seguranca Eletronica','Seguranca Patrimonial','Seguro Automotivo','Seguros','Selaria','Sementes','Semijoias','Serralheria','Servidores','Servicos de TI','Servicos Funerarios','Simuladores','Smart TV','Smartphones','Software e Licencas','Som Automotivo','Spa','Stand Up Paddle','Suplementos Alimentares','Suplementos Animais','Suporte Tecnico','Surf','Suspensao e Freios','Tablets','Tapetes e Carpetes','Teatro','Tecidos e Aviamentos','Telhados','Telefonia','Tenis de Mesa','Terapia Ocupacional','Terrarios','Tintas','Tiro Esportivo','Toners e Cartuchos','Topografia','Torneiras e Registros','Traducao','Transporte Escolar','Transporte Executivo','Trilhas e Montanhismo','Troca de Oleo','Tuning','Turismo de Aventura','Turismo Rural','Uniformes','Universidade','Utilidades Domesticas','Vans e Micro-onibus','Veiculos Eletricos','Vestuario Profissional','Veterinaria','Vidracaria','Vidro Automotivo','Vintage e Brecho','Viveiro de Plantas','Volei','Wearables','Web Design','Yoga e Pilates','Zoo e Fauna'
);

-- Passo 2: Inserir todas as 272 categorias novas
INSERT INTO public.categorias_loja (nome, icone) VALUES
('Acabamentos', '🏗️'),
('Acessorios Automotivos', '🚗'),
('Acessorios Femininos', '👜'),
('Acessorios Masculinos', '⌚'),
('Acougue', '🥩'),
('Acupuntura', '📍'),
('Adestramento', '🐕'),
('Advocacia', '⚖️'),
('Agua e Gelo', '💧'),
('Agropecuaria', '🌾'),
('Alfaiataria', '🪡'),
('Alimentos Congelados', '🧊'),
('Alimentos Fitness', '💪'),
('Alimentos Funcionais', '🥗'),
('Alimentos Importados', '🌍'),
('Alimentos Naturais', '🌿'),
('Alimentos Sem Gluten', '🌾'),
('Alimentos Sem Lactose', '🥛'),
('Alimentos Veganos', '🥑'),
('Antenas e Receptores', '📡'),
('Aquarismo', '🐠'),
('Aquecedores', '🔥'),
('Ar Condicionado', '❄️'),
('Armas e Municao', '🎯'),
('Aromaterapia', '🌸'),
('Arquitetura', '📐'),
('Artigos de Pesca', '🎣'),
('Artigos Esportivos', '🏅'),
('Assessoria Contabil', '📊'),
('Assessoria de Marketing', '📣'),
('Assistencia Tecnica', '🔧'),
('Audio e Som', '🔊'),
('Aulas de Musica', '🎵'),
('Aulas Particulares', '📚'),
('Auto Eletrica', '⚡'),
('Auto Escola', '🚗'),
('Auto Pecas', '🔧'),
('Automacao Residencial', '🏠'),
('Aventura e Ecoturismo', '🏕️'),
('Balas e Doces', '🍬'),
('Banho e Tosa', '🐩'),
('Banheiros e Metais', '🚿'),
('Baterias e Carregadores', '🔋'),
('Biblioteca', '📖'),
('Bicicletas', '🚲'),
('Bijuterias', '💍'),
('Biscoitos e Bolachas', '🍪'),
('Blindagem', '🛡️'),
('Bolos e Tortas', '🎂'),
('Bolsas e Carteiras', '👛'),
('Bone e Chapeus', '🧢'),
('Borracharia', '🛞'),
('Brinquedoteca', '🧸'),
('Cabos e Adaptadores', '🔌'),
('Cafeteria', '☕'),
('Calcados Esportivos', '👟'),
('Calcados Femininos', '👠'),
('Calcados Infantis', '🧒'),
('Calcados Masculinos', '👞'),
('Cameras e Filmadoras', '📷'),
('Caminhoes', '🚛'),
('Camping', '⛺'),
('Camisetas Personalizadas', '👕'),
('Cannabis Medicinal', '🌿'),
('Capoeira', '🥋'),
('Carnes e Embutidos', '🥩'),
('Carpintaria', '🪵'),
('Cartorio', '📜'),
('Casa de Festas', '🎉'),
('Casa de Sucos', '🧃'),
('Ceramicas e Azulejos', '🟫'),
('Cervejaria Artesanal', '🍺'),
('Chocolates', '🍫'),
('Churrasqueiras', '🔥'),
('Cirurgia Plastica', '🏥'),
('Clinica Dentaria', '🦷'),
('Clinica Dermatologica', '🩺'),
('Clinica Estetica', '💆'),
('Clinica Medica', '🏥'),
('Clinica Oftalmologica', '👁️'),
('Clinica Veterinaria', '🐾'),
('Clube Recreativo', '🏊'),
('Coaching', '🎯'),
('Coaching de Saude', '🧘'),
('Colchoes', '🛏️'),
('Colesterol e Diabetes', '💉'),
('Comida Arabe', '🧆'),
('Comida Chinesa', '🥡'),
('Comida Indiana', '🍛'),
('Comida Italiana', '🍝'),
('Comida Mexicana', '🌮'),
('Comida Nordestina', '🌽'),
('Comida Portuguesa', '🐟'),
('Comida Tailandesa', '🍜'),
('Componentes Eletronicos', '🔩'),
('Computadores', '🖥️'),
('Concessionaria', '🏢'),
('Confeitaria', '🧁'),
('Conservas e Enlatados', '🥫'),
('Consoles e Videogames', '🎮'),
('Consultoria Empresarial', '💼'),
('Contabilidade', '📋'),
('Cortinas e Persianas', '🪟'),
('Cosmeticos Naturais', '🌿'),
('Coworking', '🏢'),
('Creperia', '🥞'),
('Criacao de Aves', '🐓'),
('Criacao de Peixes', '🐟'),
('Crossfit', '🏋️'),
('Cursos Online', '💻'),
('Cursos Profissionalizantes', '📝'),
('Cursos Tecnicos', '🔧'),
('Customizacao Veicular', '🎨'),
('Danca', '💃'),
('Decoracao de Festas', '🎉'),
('Delicatessen', '🧀'),
('Dermocosmeticos', '💄'),
('Design Grafico', '🎨'),
('Desinsetizacao', '🐜'),
('Despachante', '📋'),
('Despachante Aduaneiro', '📦'),
('Distribuidora de Bebidas', '🍷'),
('Drogaria', '💊'),
('Drones', '🚁'),
('Educacao Especial', '🤝'),
('Eletricista', '⚡'),
('Emporio', '🏪'),
('Encanamento', '🔧'),
('Engenharia', '📐'),
('Envelopamento', '🚙'),
('Enxoval de Bebe', '🍼'),
('Equipamentos de Mergulho', '🤿'),
('Equipamentos de Rede', '📶'),
('Equipamentos Hospitalares', '🩺'),
('Equipamentos Ortopedicos', '🦴'),
('Equinos', '🐴'),
('Ervas e Especiarias', '🌶️'),
('Escalada', '🧗'),
('Escola de Artes', '🎨'),
('Escola de Culinaria', '👨‍🍳'),
('Escola de Esportes', '⚽'),
('Escola de Idiomas', '🗣️'),
('Escola de Natacao', '🏊'),
('Escola Infantil', '🎒'),
('Escapamentos', '💨'),
('Escritorio de Advocacia', '⚖️'),
('Estacionamento', '🅿️'),
('Estamparia', '🎨'),
('Estetica Automotiva', '🚗'),
('Estetica Capilar', '💇'),
('Estetica Facial', '✨'),
('Eventos e Producao', '🎪'),
('Faculdade', '🎓'),
('Ferragens', '🔩'),
('Fisioterapia', '🏃'),
('Flores e Plantas', '🌺'),
('Fones de Ouvido', '🎧'),
('Food Truck', '🚚'),
('Fotografia', '📸'),
('Frios e Laticinios', '🧈'),
('Frutas e Verduras', '🍎'),
('Funilaria e Pintura', '🖌️'),
('Futebol', '⚽'),
('Golfe', '⛳'),
('GPS e Navegacao', '🗺️'),
('Grafica e Impressao', '🖨️'),
('Graos e Cereais', '🌾'),
('Hamburgueria', '🍔'),
('HD e Armazenamento', '💾'),
('Homeopatia', '🌿'),
('Hortifruti', '🥬'),
('Hospedagem Pet', '🏨'),
('Iluminacao LED', '💡'),
('Imobiliaria', '🏘️'),
('Impressoras', '🖨️'),
('Ingles', '🇺🇸'),
('Insumos Agricolas', '🌱'),
('Insulfilm', '🪟'),
('Iogurteria', '🍦'),
('Jardinagem', '🌱'),
('Joalheria', '💎'),
('Kart', '🏎️'),
('Laboratorio de Analises', '🔬'),
('Laboratorio de Informatica', '🖥️'),
('Lava Rapido', '🚿'),
('Limpeza Profissional', '🧹'),
('Lingerie', '👙'),
('Livraria', '📚'),
('Locacao de Equipamentos', '🏗️'),
('Locacao de Veiculos', '🔑'),
('Logistica', '📦'),
('Loucas e Talheres', '🍽️'),
('Lubrificantes', '🛢️'),
('Lustres e Luminarias', '💡'),
('Lutas e Artes Marciais', '🥊'),
('Madeiras', '🪵'),
('Manipulacao', '💊'),
('Maquinas Agricolas', '🚜'),
('Marcenaria', '🪚'),
('Massoterapia', '💆'),
('Material de Construcao', '🧱'),
('Material Eletrico', '⚡'),
('Material Escolar', '✏️'),
('Material Hidraulico', '🚰'),
('Mecanica Diesel', '⚙️'),
('Mecanica Geral', '🔧'),
('Meditacao e Yoga', '🧘'),
('Meias e Pijamas', '🧦'),
('Moda Country', '🤠'),
('Moda Evangelica', '✝️'),
('Moda Feminina', '👗'),
('Moda Fitness', '🏋️'),
('Moda Infantil', '👶'),
('Moda Intima', '🩱'),
('Moda Masculina', '👔'),
('Moda Plus Size', '👚'),
('Moda Praia', '🏖️'),
('Moda Streetwear', '🧥'),
('Moda Sustentavel', '♻️'),
('Monitores', '🖥️'),
('Motocicletas', '🏍️'),
('Moveis de Escritorio', '🪑'),
('Moveis Planejados', '🗄️'),
('Moveis Rusticos', '🏡'),
('Mudancas e Fretes', '🚛'),
('Museu', '🏛️'),
('Nautica e Barcos', '⛵'),
('Notebooks', '💻'),
('Nutricao', '🥗'),
('Oculos de Sol', '🕶️'),
('Organizacao e Armazenamento', '📦'),
('Otica', '👓'),
('Paintball', '🔫'),
('Paisagismo', '🌳'),
('Papel de Parede', '🎨'),
('Papelaria', '📎'),
('Parque de Diversoes', '🎢'),
('Patins e Skate', '🛹'),
('Pecas para PC', '🔧'),
('Perfumaria', '🧴'),
('Perifericos', '🖱️'),
('Pet Food', '🦴'),
('Pet Shop', '🐾'),
('Pilates', '🤸'),
('Pintura e Acabamento', '🖌️'),
('Piscinas', '🏊'),
('Pneus', '🛞'),
('Portas e Janelas', '🚪'),
('Pre-Vestibular', '📝'),
('Producao de Video', '🎬'),
('Produtos Hospitalares', '🏥'),
('Produtos Ortopedicos', '🦽'),
('Projetores', '📽️'),
('Protese Dentaria', '🦷'),
('Psicologia', '🧠'),
('Publicidade', '📢'),
('Quadras Esportivas', '🏀'),
('Quiropraxia', '🦴'),
('Racao e Nutricao Animal', '🐶'),
('Radiologia', '🩻'),
('Rafting', '🛶'),
('Rastreamento Veicular', '📍'),
('Reboque e Guincho', '🚨'),
('Recursos Humanos', '👥'),
('Reformas e Obras', '🏗️'),
('Relogio Smartwatch', '⌚'),
('Relogios', '⏱️'),
('Reparos de Celular', '📱'),
('Retifica de Motores', '⚙️'),
('Robotica', '🤖'),
('Rodas e Aros', '🛞'),
('Roupas de Cama', '🛏️'),
('Roupas de Inverno', '🧤'),
('Roupas Esportivas', '🏃'),
('Roupas Sociais', '🤵'),
('Salao de Beleza', '💇'),
('Sapataria', '👢'),
('Seguranca Eletronica', '📹'),
('Seguranca Patrimonial', '🔒'),
('Seguro Automotivo', '📄'),
('Seguros', '🛡️'),
('Selaria', '🐎'),
('Sementes', '🌱'),
('Semijoias', '📿'),
('Serralheria', '⚙️'),
('Servidores', '🖧'),
('Servicos de TI', '💻'),
('Servicos Funerarios', '⚱️'),
('Simuladores', '🕹️'),
('Smart TV', '📺'),
('Smartphones', '📲'),
('Software e Licencas', '💿'),
('Som Automotivo', '🔊'),
('Spa', '🧖'),
('Stand Up Paddle', '🏄'),
('Suplementos Alimentares', '💪'),
('Suplementos Animais', '💊'),
('Suporte Tecnico', '🛠️'),
('Surf', '🏄'),
('Suspensao e Freios', '🛑'),
('Tablets', '📋'),
('Tapetes e Carpetes', '🟤'),
('Teatro', '🎭'),
('Tecidos e Aviamentos', '🧵'),
('Telhados', '🏠'),
('Telefonia', '☎️'),
('Tenis de Mesa', '🏓'),
('Terapia Ocupacional', '🤲'),
('Terrarios', '🦎'),
('Tintas', '🎨'),
('Tiro Esportivo', '🎯'),
('Toners e Cartuchos', '🖨️'),
('Topografia', '🗺️'),
('Torneiras e Registros', '🚰'),
('Traducao', '🌐'),
('Transporte Escolar', '🚌'),
('Transporte Executivo', '🚗'),
('Trilhas e Montanhismo', '⛰️'),
('Troca de Oleo', '🛢️'),
('Tuning', '🏎️'),
('Turismo de Aventura', '🏔️'),
('Turismo Rural', '🏡'),
('Uniformes', '👷'),
('Universidade', '🏫'),
('Utilidades Domesticas', '🏡'),
('Vans e Micro-onibus', '🚐'),
('Veiculos Eletricos', '🔋'),
('Vestuario Profissional', '🥼'),
('Veterinaria', '🐾'),
('Vidracaria', '🪟'),
('Vidro Automotivo', '🪟'),
('Vintage e Brecho', '🛍️'),
('Viveiro de Plantas', '🌺'),
('Volei', '🏐'),
('Wearables', '⌚'),
('Web Design', '🌐'),
('Yoga e Pilates', '🧘'),
('Zoo e Fauna', '🦜');

-- =====================================================================
-- Verificacao final
-- =====================================================================
-- SELECT COUNT(*) AS total_categorias FROM public.categorias_loja;
-- Esperado: 300
