-- ============================================================
-- ORION-HARDENING FASE 2 · ETAPA 2 — Menor privilégio em RPCs DEFINER · 2026-07-19
-- Base: FASE 1 (R2) + HOTFIX A.0 (declarou 1.116 fns anon). Esta migration fecha
-- o vetor de MUTAÇÃO anônima nas funções DEFINER fora dos domínios já tratados.
-- Inventário vivo: 1005 DEFINER não-trigger exec. por anon; 421 mutam; 204 sem guarda.
-- Destas 204: 8 são superfície PÚBLICA legítima (interest-click/inquiry/order) → MANTIDAS;
-- 196 não têm caminho anônimo legítimo (grep .rpc em src+Edge) → REVOKE anon.
-- 2 são financeiras (split de pagamento) → REVOKE anon+authenticated (só service_role).
-- +2 leituras sensíveis (mp_get_admin_overview, is_admin_user) → REVOKE anon.
-- service_role e owner mantidos: motor/cron/trigger/Edge intactos (chamadas internas
-- de DEFINER e triggers executam como owner, independentes do grant).
-- SEM DDL de tabela/função. SEM regra de negócio. Idempotente. SQL Editor.
-- ============================================================

-- BLOCO 1 · 2 financeiras (split de pagamento): revoke anon+authenticated
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_motoboy_split_transaction(uuid,numeric,numeric,uuid,uuid,uuid,text,jsonb) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.create_motoboy_split_transaction(uuid,numeric,numeric,uuid,uuid,uuid,text,jsonb) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_motoboy_split_transaction(uuid,numeric,numeric,uuid,uuid,uuid,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.release_service_payment_split(uuid,uuid,numeric,numeric) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.release_service_payment_split(uuid,uuid,numeric,numeric) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: release_service_payment_split(uuid,uuid,numeric,numeric)'; END $$;

-- BLOCO 2 · 2 leituras sensíveis admin: revoke anon
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mp_get_admin_overview() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mp_get_admin_overview()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_admin_user(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_admin_user(uuid)'; END $$;

-- BLOCO 3 · 194 funções mutantes sem caminho anônimo: revoke anon (authenticated mantido = zero breakage)
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.accept_delivery_offer_v2(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: accept_delivery_offer_v2(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.accept_delivery_order(uuid,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: accept_delivery_order(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.add_item_to_store_cart(uuid,uuid,integer,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: add_item_to_store_cart(uuid,uuid,integer,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ai_center_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ai_center_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ai_engine_complete(uuid,jsonb,text,integer,integer,integer,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ai_engine_complete(uuid,jsonb,text,integer,integer,integer,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ai_visibility_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ai_visibility_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_automate() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_automate()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_predict() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_predict()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_refresh_health() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_refresh_health()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_register_anomaly(text,text,text,text,text,jsonb,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_register_anomaly(text,text,text,text,text,jsonb,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aiops_statistics_rollup(jsonb,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aiops_statistics_rollup(jsonb,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_alert_put(text,text,text,text,integer,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_alert_put(text,text,text,text,integer,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_dispatch(bigint,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_dispatch(bigint,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_event_put(text,text,text,text,text,jsonb,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_event_put(text,text,text,text,text,jsonb,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_open_incident(text,text,text,bigint,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_open_incident(text,text,text,bigint,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_recover(bigint,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_recover(bigint,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_resource_put(text,text,numeric,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_resource_put(text,text,numeric,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: aoc_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.apply_postador3_price_to_delivery_order(uuid,numeric) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: apply_postador3_price_to_delivery_order(uuid,numeric)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.apply_pricing_to_delivery_order(uuid,numeric,integer,text,delivery_service_level) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: apply_pricing_to_delivery_order(uuid,numeric,integer,text,delivery_service_level)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.assign_campaign_to_motoboy(uuid,uuid,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: assign_campaign_to_motoboy(uuid,uuid,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.auto_cancel_stale_deliveries() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: auto_cancel_stale_deliveries()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.auto_dispatch_campaign_by_service_area(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: auto_dispatch_campaign_by_service_area(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.automation_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: automation_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backfill_campaign_queue_to_dispatch(uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: backfill_campaign_queue_to_dispatch(uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backfill_products_to_campaign_queue(uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: backfill_products_to_campaign_queue(uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backup_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: backup_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backup_generate_alerts() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: backup_generate_alerts()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backup_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: backup_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.bg_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: bg_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.bi_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: bi_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.charge_real_estate_interest_click(uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: charge_real_estate_interest_click(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.charge_real_estate_listing_click(uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: charge_real_estate_listing_click(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.claim_next_campaign_queue(uuid,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: claim_next_campaign_queue(uuid,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.command_c_register_event(text,uuid,uuid,uuid,text,numeric,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: command_c_register_event(text,uuid,uuid,uuid,text,numeric,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.complete_service_order(uuid,uuid,numeric) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: complete_service_order(uuid,uuid,numeric)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.confirm_posting_with_cooldown(uuid,uuid,uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: confirm_posting_with_cooldown(uuid,uuid,uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.confirm_topup(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: confirm_topup(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.confirmar_postagem(uuid,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: confirmar_postagem(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_advertiser_campaign_queue_item(uuid,text,uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_advertiser_campaign_queue_item(uuid,text,uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_campaign_queue_item(uuid,uuid,uuid,uuid,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,integer,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_campaign_queue_item(uuid,uuid,uuid,uuid,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,integer,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_delivery_offers_for_order(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_delivery_offers_for_order(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_delivery_offers_for_order(uuid,uuid[],integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_delivery_offers_for_order(uuid,uuid[],integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_merchant_campaign_queue_item(uuid,uuid,uuid,text,text,text,text,text,text,integer,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_merchant_campaign_queue_item(uuid,uuid,uuid,text,text,text,text,text,text,integer,timestamp with time zone,timestamp with time zone,timestamp with time zone,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_merchant_marketing_product(uuid,uuid,text,text,text,text,text,text,text,text,text,text,boolean,integer,timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_merchant_marketing_product(uuid,uuid,text,text,text,text,text,text,text,text,text,text,boolean,integer,timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_posting_batch_for_motoboy(uuid,integer,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_posting_batch_for_motoboy(uuid,integer,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_purchase_intention_with_consumer(uuid,text,text,text,text,text,text,boolean,boolean,boolean,boolean,jsonb,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_purchase_intention_with_consumer(uuid,text,text,text,text,text,text,boolean,boolean,boolean,boolean,jsonb,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.create_store_menu_notification(uuid,uuid,text,text,text,text,text,uuid,jsonb,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: create_store_menu_notification(uuid,uuid,text,text,text,text,text,uuid,jsonb,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.cs_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: cs_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.cyber_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: cyber_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_campaign_to_city_region(uuid,text,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_campaign_to_city_region(uuid,text,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_campaign_to_user(uuid,uuid,text,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_campaign_to_user(uuid,uuid,text,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_create_offers(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_create_offers(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_create_offers_h3(uuid,text[],integer,numeric,integer,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_create_offers_h3(uuid,text[],integer,numeric,integer,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_run_round(uuid,integer,numeric,integer,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_run_round(uuid,integer,numeric,integer,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.dispatch_to_next_motoboy(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: dispatch_to_next_motoboy(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.enqueue_merchant_marketing_campaign(uuid,uuid,text,text,text,text,text,integer,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: enqueue_merchant_marketing_campaign(uuid,uuid,text,text,text,text,text,integer,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.enqueue_notification_event(text,text,uuid,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: enqueue_notification_event(text,text,uuid,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.enqueue_product_campaign_for_posting(uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: enqueue_product_campaign_for_posting(uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.enqueue_product_to_postador(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: enqueue_product_to_postador(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_group_posting_runtime(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_group_posting_runtime(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_merchant_profile(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_merchant_profile(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_merchant_store(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_merchant_store(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_motoboy_profile(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_motoboy_profile(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_platform_master_account() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_platform_master_account()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_postador_batch_runtime(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_postador_batch_runtime(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.execution_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: execution_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.executive_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: executive_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.expire_delivery_offers_for_order(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: expire_delivery_offers_for_order(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_build_decisions() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_build_decisions()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_build_opportunities() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_build_opportunities()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_build_risks() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_build_risks()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_build_scenarios() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_build_scenarios()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_learn() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_learn()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_refresh_ai_summary() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_refresh_ai_summary()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_report_generate(text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_report_generate(text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_scores_refresh() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_scores_refresh()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.exstrat_snapshot() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: exstrat_snapshot()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.flag_review_advertiser_media(uuid,text,text,numeric,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: flag_review_advertiser_media(uuid,text,text,numeric,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_bridge_cyber() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_bridge_cyber()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_patterns_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_patterns_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_register(text,text,text,text,bigint,bigint,bigint,bigint,numeric,jsonb,text,uuid,uuid,uuid,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_register(text,text,text,text,bigint,bigint,bigint,bigint,numeric,jsonb,text,uuid,uuid,uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_respond() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_respond()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fraud_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fraud_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.generate_posting_lots() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: generate_posting_lots()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.generate_recommendations(uuid,text,text,text,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: generate_recommendations(uuid,text,text,text,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.geo_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: geo_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.governance_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: governance_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.identity_bridge_cyber() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: identity_bridge_cyber()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.identity_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: identity_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.identity_event(text,text,bigint,jsonb,text,uuid,uuid,text,text,text,text,timestamp with time zone) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: identity_event(text,text,bigint,jsonb,text,uuid,uuid,text,text,text,text,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.identity_respond() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: identity_respond()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.identity_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: identity_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.innovation_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: innovation_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.insert_posting_history_from_queue(uuid,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: insert_posting_history_from_queue(uuid,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.janela_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: janela_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.kg_add_edge(text,text,text,bigint,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: kg_add_edge(text,text,text,bigint,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.kg_add_node(text,text,text,text,text,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: kg_add_node(text,text,text,text,text,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.kg_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: kg_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.kg_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: kg_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.knowledge_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: knowledge_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.learning_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: learning_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.log_campaign_queue_event(uuid,text,text,text,uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: log_campaign_queue_event(uuid,text,text,text,uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.logistics_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: logistics_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.m1_track_event(uuid,uuid,uuid,text,text,text,text,uuid,uuid,text,text,text,uuid,numeric,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: m1_track_event(uuid,uuid,uuid,text,text,text,text,uuid,uuid,text,text,text,uuid,numeric,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mark_campaign_as_failed(uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mark_campaign_as_failed(uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mark_campaign_as_posted(uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mark_campaign_as_posted(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.market_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: market_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mkt_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mkt_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.motor_emit(uuid,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: motor_emit(uuid,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_alert_put(text,text,text,text,text,integer,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_alert_put(text,text,text,text,text,integer,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_collect_traces() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_collect_traces()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_health_refresh() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_health_refresh()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_ingest_logs() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_ingest_logs()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_log_ingest(text,text,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_log_ingest(text,text,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_metric_put(text,text,numeric,text,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_metric_put(text,text,numeric,text,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_sli_put(text,text,text,numeric,text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_sli_put(text,text,text,numeric,text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_sli_slo_refresh() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_sli_slo_refresh()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.obs_trace_ingest(text,text,text,integer,text,timestamp with time zone,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: obs_trace_ingest(text,text,text,integer,text,timestamp with time zone,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.oce_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: oce_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.operations_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: operations_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_ai_visibility_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_ai_visibility_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_bg_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_bg_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_campaign_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_campaign_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_campaign_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_campaign_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_dispatch_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_dispatch_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_dispatcher_liberar_workers() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_dispatcher_liberar_workers()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_dispatcher_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_dispatcher_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_forecast_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_forecast_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_growth_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_growth_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_growth_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_growth_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_package_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_package_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_perf_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_perf_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_recommendation_tick() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_recommendation_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.perso_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: perso_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.pricing_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: pricing_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.radar_apply_ia_verdict(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: radar_apply_ia_verdict(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.recalculate_store_cart(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: recalculate_store_cart(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.recommendation_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: recommendation_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.recommendation_event(uuid,text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: recommendation_event(uuid,text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.register_lot_click(text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: register_lot_click(text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.register_postador_action(uuid,uuid,uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: register_postador_action(uuid,uuid,uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.release_campaign_processing(uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: release_campaign_processing(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.release_expired_claims() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: release_expired_claims()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reset_advertiser_media_for_analysis(uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reset_advertiser_media_for_analysis(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reset_posting_batch_countdowns(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reset_posting_batch_countdowns(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.rpc_register_property_click(uuid,text,integer) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: rpc_register_property_click(uuid,text,integer)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.sales_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: sales_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.search_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: search_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.search_semantic(text,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: search_semantic(text,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.sec_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: sec_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.seed_campaign_posting_targets() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: seed_campaign_posting_targets()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.seed_campaign_posting_targets_debug() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: seed_campaign_posting_targets_debug()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.select_posting_candidate(uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: select_posting_candidate(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.semantic_search(text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: semantic_search(text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.send_campaign_to_review(uuid,uuid,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: send_campaign_to_review(uuid,uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.soc_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: soc_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.soc_statistics_rollup(jsonb,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: soc_statistics_rollup(jsonb,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.submit_multi_store_intention(text,text,text,text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: submit_multi_store_intention(text,text,text,text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.submit_purchase_intention(uuid,text,text,text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: submit_purchase_intention(uuid,text,text,text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.support_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: support_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.sustainability_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: sustainability_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_add_edge(text,text,text,jsonb,bigint,bigint,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_add_edge(text,text,text,jsonb,bigint,bigint,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_add_node(text,text,text,bigint,text,jsonb,bigint,timestamp with time zone,timestamp with time zone,timestamp with time zone,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_add_node(text,text,text,bigint,text,jsonb,bigint,timestamp with time zone,timestamp with time zone,timestamp with time zone,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_scan_intelligence() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_scan_intelligence()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_scan_vulnerabilities() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_scan_vulnerabilities()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.threat_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: threat_statistics_rollup()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.transition_campaign_queue_status(uuid,text,text,text,uuid,text,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: transition_campaign_queue_status(uuid,text,text,text,uuid,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.trust_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: trust_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.try_create_driver_whatsapp_group(text,text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: try_create_driver_whatsapp_group(text,text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.try_create_merchant_whatsapp_group(text,text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: try_create_merchant_whatsapp_group(text,text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.try_create_motoboy_whatsapp_group(text,text,text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: try_create_motoboy_whatsapp_group(text,text,text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.try_create_whatsapp_group(text,text,text,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: try_create_whatsapp_group(text,text,text,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.update_ride_pricing_config(uuid,numeric,numeric,numeric,numeric,numeric) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: update_ride_pricing_config(uuid,numeric,numeric,numeric,numeric,numeric)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.update_store_cart_item(uuid,integer,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: update_store_cart_item(uuid,integer,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.upsert_consumer_light_account(text,text,text,text,text,text,boolean,boolean,boolean,boolean) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: upsert_consumer_light_account(text,text,text,text,text,text,boolean,boolean,boolean,boolean)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.validate_pickup_code(character varying,uuid) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: validate_pickup_code(character varying,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.visitor_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: visitor_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_alert_emit(text,text,text,numeric) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_alert_emit(text,text,text,numeric)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_context_refresh() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_context_refresh()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_devices_evaluate() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_devices_evaluate()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_emit(text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_evidence(text,text,jsonb) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_evidence(text,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_risk_refresh() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_risk_refresh()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_sessions_evaluate() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_sessions_evaluate()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.zerotrust_statistics_rollup() FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: zerotrust_statistics_rollup()'; END $$;

-- VERIFICAÇÃO (esperado: anon_mut_noguard baixo — só as 8 públicas + drift)
SELECT
 (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
   WHERE n.nspname='public' AND p.prosecdef AND p.prorettype<>'trigger'::regtype
     AND has_function_privilege('anon',p.oid,'EXECUTE')
     AND (p.prosrc ~* 'insert into|update |delete from|truncate')
     AND NOT (p.prosrc ~* 'auth\.uid|is_admin|is_platform_admin|has_role|assert|guard')) AS anon_mut_noguard_restante,
 (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
   WHERE n.nspname='public' AND p.prosecdef AND p.prorettype<>'trigger'::regtype
     AND has_function_privilege('anon',p.oid,'EXECUTE')
     AND (p.proname ~* 'split|payment_split|motoboy_split')) AS anon_fin_split_restante;
