-- Migration: Add AI fields for support tickets
-- This allows the system to track AI status and identify messages sent by the AI.

-- Add ai_status to support_tickets
-- Possible values: 'pending', 'answered', 'escalated'
ALTER TABLE public.support_tickets
ADD COLUMN IF NOT EXISTS ai_status text DEFAULT 'pending';

-- Add is_ai to ticket_messages to visually distinguish them
ALTER TABLE public.ticket_messages
ADD COLUMN IF NOT EXISTS is_ai boolean DEFAULT false;

-- Add a comment to columns for documentation
COMMENT ON COLUMN public.support_tickets.ai_status IS 'Status of the AI handling the ticket: pending, answered, escalated';
COMMENT ON COLUMN public.ticket_messages.is_ai IS 'Indicates if the message was generated by the automated AI system';
