-- ============================================================
-- ORION-HARDENING FASE 1 · P0-2b: revogar anon de RPCs SENSÍVEIS (não pegas pela regra financeira) · 2026-07-18
-- Contexto: além das 93 financeiras, 69 funções SECURITY DEFINER sensíveis
-- (admin_*, ajustes financeiros, moderação, e-mails de usuário, dispatch de campanha,
-- profit events) eram EXECUTÁVEIS por anon. Destaques SEM guarda: admin_apply_financial_adjustment
-- (move dinheiro), admin_get_auth_emails (vaza e-mail/PII), track_admin_profit_event (injeta receita),
-- approve/reject_advertiser_media (bypass de moderação). cyber_block_entity tem cyber_guard(); demais admin_get_*
-- com admin_assert_access. Ainda assim: anon não deve alcançá-las.
-- Decisão: revoke anon em todas; revoke authenticated nas 65 não chamadas por front/Edge
-- (comprovado por grep .rpc); mantém authenticated nas 4 chamadas pelo front; service_role sempre.
-- Reversível. Idempotente. SQL Editor (broifhfqmnzqoongtokm).
-- ============================================================

-- ETAPA A · 4 sensíveis chamadas pelo front: revoga anon/PUBLIC, mantém authenticated
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_auth_emails(uuid[]) FROM PUBLIC, anon'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_auth_emails(uuid[]) TO authenticated, service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_auth_emails(uuid[])'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot_rpc(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot_rpc(timestamp with time zone,timestamp with time zone) TO authenticated, service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_dashboard_snapshot_rpc(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reject_delivery_offer(uuid) FROM PUBLIC, anon'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.reject_delivery_offer(uuid) TO authenticated, service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reject_delivery_offer(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mp_is_admin() FROM PUBLIC, anon'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.mp_is_admin() TO authenticated, service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mp_is_admin()'; END $$;

-- ETAPA B · 65 sensíveis internas (nenhum .rpc no front/Edge): revoga anon E authenticated
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_financial_account() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.ensure_financial_account() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_financial_account()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_ensure_financial_account(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_ensure_financial_account(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_ensure_financial_account(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.get_financial_profile_overview() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.get_financial_profile_overview() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: get_financial_profile_overview()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.sandbox_get_financial_profile_overview(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.sandbox_get_financial_profile_overview(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: sandbox_get_financial_profile_overview(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.recalculate_financial_balance(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.recalculate_financial_balance(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: recalculate_financial_balance(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_apply_financial_adjustment(uuid,text,bigint,admin_financial_prefix,admin_financial_complement) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_apply_financial_adjustment(uuid,text,bigint,admin_financial_prefix,admin_financial_complement) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_apply_financial_adjustment(uuid,text,bigint,admin_financial_prefix,admin_financial_complement)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_apply_financial_adjustment(uuid,bigint,admin_financial_prefix,admin_financial_complement) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_apply_financial_adjustment(uuid,bigint,admin_financial_prefix,admin_financial_complement) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_apply_financial_adjustment(uuid,bigint,admin_financial_prefix,admin_financial_complement)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.ensure_financial_account(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.ensure_financial_account(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: ensure_financial_account(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.process_delivery_financial_split(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.process_delivery_financial_split(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: process_delivery_financial_split(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.approve_campaign_queue_item(uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.approve_campaign_queue_item(uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: approve_campaign_queue_item(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.cancel_campaign_dispatch(uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.cancel_campaign_dispatch(uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: cancel_campaign_dispatch(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_start_campaign_dispatch(uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_start_campaign_dispatch(uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_start_campaign_dispatch(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_mark_campaign_dispatch_posted(uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_mark_campaign_dispatch_posted(uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_mark_campaign_dispatch_posted(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.start_campaign_dispatch(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.start_campaign_dispatch(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: start_campaign_dispatch(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mark_campaign_dispatch_posted(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_campaign_dispatch_posted(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mark_campaign_dispatch_posted(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fail_campaign_dispatch(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.fail_campaign_dispatch(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fail_campaign_dispatch(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.start_campaign_dispatch_admin_test(uuid,uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.start_campaign_dispatch_admin_test(uuid,uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: start_campaign_dispatch_admin_test(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.mark_campaign_dispatch_posted_admin_test(uuid,uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.mark_campaign_dispatch_posted_admin_test(uuid,uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: mark_campaign_dispatch_posted_admin_test(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.fail_campaign_dispatch_admin_test(uuid,uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.fail_campaign_dispatch_admin_test(uuid,uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: fail_campaign_dispatch_admin_test(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_financial_admin(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_financial_admin(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_financial_admin(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_is_allowed() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_is_allowed() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_is_allowed()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_assert_access() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_assert_access() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_assert_access()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_store_overview(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_store_overview(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_store_overview(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_store_overview(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_store_overview(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_store_overview(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_store_overview(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_store_overview(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_store_overview(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.track_admin_profit_event(text,numeric,numeric,numeric,integer,uuid,text,uuid,jsonb) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.track_admin_profit_event(text,numeric,numeric,numeric,integer,uuid,text,uuid,jsonb) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: track_admin_profit_event(text,numeric,numeric,numeric,integer,uuid,text,uuid,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_product_overview(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_product_overview(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_product_overview(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_product_overview(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_product_overview(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_product_overview(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_product_overview(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_product_overview(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_product_overview(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_listing_overview(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_listing_overview(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_listing_overview(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_listing_overview(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_listing_overview(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_listing_overview(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_listing_overview(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_listing_overview(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_listing_overview(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_market_intelligence(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_market_intelligence(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_market_intelligence(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_market_intelligence(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_market_intelligence(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_market_intelligence(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_market_intelligence(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_market_intelligence(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_market_intelligence(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_profit_overview(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_profit_overview(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_profit_overview(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_profit_overview(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_profit_overview(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_profit_overview(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_profit_overview(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_profit_overview(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_profit_overview(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(timestamp with time zone,timestamp with time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_dashboard_snapshot(timestamp with time zone,timestamp with time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(timestamp without time zone,timestamp without time zone) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(timestamp without time zone,timestamp without time zone) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_dashboard_snapshot(timestamp without time zone,timestamp without time zone)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(date,date) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_get_dashboard_snapshot(date,date) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_get_dashboard_snapshot(date,date)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_dashboard_overview() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_dashboard_overview() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_dashboard_overview()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reject_delivery_offer_v2(uuid,uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.reject_delivery_offer_v2(uuid,uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reject_delivery_offer_v2(uuid,uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reject_delivery_offer_v2(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.reject_delivery_offer_v2(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reject_delivery_offer_v2(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.approve_advertiser_media(uuid,numeric,text,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.approve_advertiser_media(uuid,numeric,text,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: approve_advertiser_media(uuid,numeric,text,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reject_advertiser_media(uuid,text,text,numeric,text,jsonb) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.reject_advertiser_media(uuid,text,text,numeric,text,jsonb) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: reject_advertiser_media(uuid,text,text,numeric,text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_current_user_admin() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_current_user_admin()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_list_merchant_balances() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_list_merchant_balances() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_list_merchant_balances()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_email_admin() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_email_admin() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_email_admin()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_force_release_claim(uuid) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_force_release_claim(uuid) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_force_release_claim(uuid)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_list_motoboy_finances() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_list_motoboy_finances() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_list_motoboy_finances()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_admin() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_admin()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.is_platform_admin() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.is_platform_admin() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: is_platform_admin()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_fila_divulgacoes() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_fila_divulgacoes() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_fila_divulgacoes()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_auditoria_categorias() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_auditoria_categorias() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_auditoria_categorias()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.admin_corrigir_categoria(uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.admin_corrigir_categoria(uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: admin_corrigir_categoria(uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_emit(text,jsonb) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_emit(text,jsonb) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_emit(text,jsonb)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_conciliar() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_conciliar() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_conciliar()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_fraude() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_fraude() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_fraude()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_dashboard() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_dashboard() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_dashboard()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_resolver(text,uuid,text) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_resolver(text,uuid,text) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_resolver(text,uuid,text)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.orion_finance_tick() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.orion_finance_tick() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: orion_finance_tick()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.bi_financial() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.bi_financial() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: bi_financial()'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.cyber_block_entity(text,text,text,text,integer,jsonb,bigint) FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.cyber_block_entity(text,text,text,text,integer,jsonb,bigint) TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: cyber_block_entity(text,text,text,text,integer,jsonb,bigint)'; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.agrowth_assert_admin() FROM PUBLIC, anon, authenticated'; EXECUTE 'GRANT EXECUTE ON FUNCTION public.agrowth_assert_admin() TO service_role'; EXCEPTION WHEN undefined_function OR undefined_object THEN RAISE WARNING 'ausente: agrowth_assert_admin()'; END $$;

-- VERIFICAÇÃO (esperado sensiveis_anon=0)
SELECT count(*) AS sensiveis_anon FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname='public' AND p.prosecdef AND p.prorettype<>'trigger'::regtype
  AND has_function_privilege('anon', p.oid,'EXECUTE')
  AND (p.proname ~* '^admin_|_admin$|^delete_|^drop_|^approve_|^reject_|^moderat|financial|profit|balance|finance|auth_email|merchant_balance|motoboy_finance|payout|dispatch_admin|campaign_dispatch|_block_entity|bi_financial');

-- Adendo · 2 aprovações guardadas (backup/aoc) — defesa em profundidade, revoga anon
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.backup_approve_recovery(bigint,boolean,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN NULL; END $$;
DO $$ BEGIN EXECUTE 'REVOKE EXECUTE ON FUNCTION public.aoc_approve_decision(bigint,boolean,text) FROM PUBLIC, anon'; EXCEPTION WHEN undefined_function OR undefined_object THEN NULL; END $$;
