-- ═════════════════════════════════════════════════════════════
-- MIGRATION: 20260331_FINAL_FIX_V4.sql
-- V4: Nome de coluna correto (motoboy_id) em motoboy_presence
-- ═════════════════════════════════════════════════════════════
