-- ============================================================================
-- FRETES - MONETIZACAO OFICIAL  ::  NEUTRALIZADA (NO-OP) - 2026-07-23
-- ----------------------------------------------------------------------------
-- CERTIFICACAO ORION: esta migration foi ANULADA de proposito.
--
-- Motivo: toda a monetizacao oficial de fretes (Aceitar Servico e Abrir
-- Contato, comissao parametrizavel, desbloqueio de contato, preview) JA e
-- criada pela migration BASE:
--
--     supabase/migrations/20260722_freight_quotes.sql   (secao V2.1, L724-878)
--
-- que define, de forma canonica e reproduzivel:
--   * tabela  public.freight_quote_unlocks          (dedup 1x por transportador)
--   * RPC     public.preview_freight_commission      (comissao antes do aceite)
--   * RPC     public.accept_freight_opportunity_unlock (aceita + libera contato)
--   * RPC     public.get_freight_quote_contact       (rever contato liberado)
--   * fn      public.build_freight_quote_contact     (payload de contato, interna)
--   * seed    freight_commission_settings id=1       (INSERT ... ON CONFLICT, L450)
--
-- A versao anterior DESTE arquivo criava objetos PARALELOS e CONFLITANTES
-- (freight_contact_unlocks, freight_accept_and_unlock, list_freight_open_requests,
-- freight_commission_preview) e reescrevia policies da base. Manter os dois
-- geraria funcoes duplicadas, tabelas de unlock divergentes e RLS instavel.
--
-- Decisao (auditoria de reprodutibilidade): a BASE e a unica fonte de verdade.
-- Os complementos que NAO existem na base (debito real na carteira pay_* e
-- pacotes de divulgacao) foram movidos para migrations proprias e idempotentes:
--   * 20260723_freight_wallet_debito_comissao_oficial.sql  (Fase 6 - Wallet+Ledger)
--   * 20260723_promotion_core_tables_reproducibility.sql   (tabelas P0 + pacotes)
--
-- Este arquivo permanece no historico como NO-OP para nao quebrar a ordem de
-- versionamento em bancos onde ele ja possa ter sido parcialmente aplicado.
-- Nada aqui cria, altera ou remove objetos.
-- ============================================================================

SELECT 'freight_monetizacao_oficial: no-op (ver 20260722_freight_quotes.sql V2.1)'::text AS nota;
